name: app_template
description: "App项目模板"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  # 默认依赖
  cupertino_icons: ^1.0.2
  # 第三方依赖
  get: ^4.6.6 # 状态管理
  shared_preferences: ^2.2.2 # 本地存储
  dio: ^5.4.0 # Http请求
  bot_toast: ^4.1.3 # 提示库
  url_launcher: ^6.2.2 # 跳转第三方应用
  file_selector: ^1.0.1 # 文件选择器
  easy_image_viewer: ^1.3.2 # 图片预览功能
  flutter_localizations:
    sdk: flutter
  intl: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # 资源目录
  assets:
     - assets/images/
  fonts:
    - family: MyFont
      fonts:
        - asset: assets/font/NotoSansSC-Regular.ttf

