
var CanvasKitInit = (() => {
  var _scriptDir = import.meta.url;
  
  return (
async function(moduleArg = {}) {

var r=moduleArg,aa,ba;r.ready=new Promise((a,b)=>{aa=a;ba=b});
(function(a){a.ae=a.ae||[];a.ae.push(function(){a.MakeSWCanvasSurface=function(b){var c=b,d="undefined"!==typeof OffscreenCanvas&&c instanceof OffscreenCanvas;if(!("undefined"!==typeof HTMLCanvasElement&&c instanceof HTMLCanvasElement||d||(c=document.getElementById(b),c)))throw"Canvas with id "+b+" was not found";if(b=a.MakeSurface(c.width,c.height))b.Ce=c;return b};a.MakeCanvasSurface||(a.MakeCanvasSurface=a.MakeSWCanvasSurface);a.MakeSurface=function(b,c){var d={width:b,height:c,colorType:a.ColorType.RGBA_8888,
alphaType:a.AlphaType.Unpremul,colorSpace:a.ColorSpace.SRGB},f=b*c*4,k=a._malloc(f);if(d=a.Surface._makeRasterDirect(d,k,4*b))d.Ce=null,d.jf=b,d.ff=c,d.gf=f,d.Ne=k,d.getCanvas().clear(a.TRANSPARENT);return d};a.MakeRasterDirectSurface=function(b,c,d){return a.Surface._makeRasterDirect(b,c.byteOffset,d)};a.Surface.prototype.flush=function(b){a.Yd(this.Xd);this._flush();if(this.Ce){var c=new Uint8ClampedArray(a.HEAPU8.buffer,this.Ne,this.gf);c=new ImageData(c,this.jf,this.ff);b?this.Ce.getContext("2d").putImageData(c,
0,0,b[0],b[1],b[2]-b[0],b[3]-b[1]):this.Ce.getContext("2d").putImageData(c,0,0)}};a.Surface.prototype.dispose=function(){this.Ne&&a._free(this.Ne);this.delete()};a.Yd=a.Yd||function(){};a.De=a.De||function(){return null}})})(r);
(function(a){a.ae=a.ae||[];a.ae.push(function(){function b(m,p,x){return m&&m.hasOwnProperty(p)?m[p]:x}function c(m){var p=da(ea);ea[p]=m;return p}function d(m){return m.naturalHeight||m.videoHeight||m.displayHeight||m.height}function f(m){return m.naturalWidth||m.videoWidth||m.displayWidth||m.width}function k(m,p,x,y){m.bindTexture(m.TEXTURE_2D,p);y||x.alphaType!==a.AlphaType.Premul||m.pixelStorei(m.UNPACK_PREMULTIPLY_ALPHA_WEBGL,!0);return p}function l(m,p,x){x||p.alphaType!==a.AlphaType.Premul||
m.pixelStorei(m.UNPACK_PREMULTIPLY_ALPHA_WEBGL,!1);m.bindTexture(m.TEXTURE_2D,null)}a.GetWebGLContext=function(m,p){if(!m)throw"null canvas passed into makeWebGLContext";var x={alpha:b(p,"alpha",1),depth:b(p,"depth",1),stencil:b(p,"stencil",8),antialias:b(p,"antialias",0),premultipliedAlpha:b(p,"premultipliedAlpha",1),preserveDrawingBuffer:b(p,"preserveDrawingBuffer",0),preferLowPowerToHighPerformance:b(p,"preferLowPowerToHighPerformance",0),failIfMajorPerformanceCaveat:b(p,"failIfMajorPerformanceCaveat",
0),enableExtensionsByDefault:b(p,"enableExtensionsByDefault",1),explicitSwapControl:b(p,"explicitSwapControl",0),renderViaOffscreenBackBuffer:b(p,"renderViaOffscreenBackBuffer",0)};x.majorVersion=p&&p.majorVersion?p.majorVersion:"undefined"!==typeof WebGL2RenderingContext?2:1;if(x.explicitSwapControl)throw"explicitSwapControl is not supported";m=fa(m,x);if(!m)return 0;ha(m);v.ie.getExtension("WEBGL_debug_renderer_info");return m};a.deleteContext=function(m){v===ia[m]&&(v=null);"object"==typeof JSEvents&&
JSEvents.Nf(ia[m].ie.canvas);ia[m]&&ia[m].ie.canvas&&(ia[m].ie.canvas.cf=void 0);ia[m]=null};a._setTextureCleanup({deleteTexture:function(m,p){var x=ea[p];x&&ia[m].ie.deleteTexture(x);ea[p]=null}});a.MakeWebGLContext=function(m){if(!this.Yd(m))return null;var p=this._MakeGrContext();if(!p)return null;p.Xd=m;var x=p.delete.bind(p);p["delete"]=function(){a.Yd(this.Xd);x()}.bind(p);return v.Pe=p};a.MakeGrContext=a.MakeWebGLContext;a.GrDirectContext.prototype.getResourceCacheLimitBytes=function(){a.Yd(this.Xd);
this._getResourceCacheLimitBytes()};a.GrDirectContext.prototype.getResourceCacheUsageBytes=function(){a.Yd(this.Xd);this._getResourceCacheUsageBytes()};a.GrDirectContext.prototype.releaseResourcesAndAbandonContext=function(){a.Yd(this.Xd);this._releaseResourcesAndAbandonContext()};a.GrDirectContext.prototype.setResourceCacheLimitBytes=function(m){a.Yd(this.Xd);this._setResourceCacheLimitBytes(m)};a.MakeOnScreenGLSurface=function(m,p,x,y,B,D){if(!this.Yd(m.Xd))return null;p=void 0===B||void 0===D?
this._MakeOnScreenGLSurface(m,p,x,y):this._MakeOnScreenGLSurface(m,p,x,y,B,D);if(!p)return null;p.Xd=m.Xd;return p};a.MakeRenderTarget=function(){var m=arguments[0];if(!this.Yd(m.Xd))return null;if(3===arguments.length){var p=this._MakeRenderTargetWH(m,arguments[1],arguments[2]);if(!p)return null}else if(2===arguments.length){if(p=this._MakeRenderTargetII(m,arguments[1]),!p)return null}else return null;p.Xd=m.Xd;return p};a.MakeWebGLCanvasSurface=function(m,p,x){p=p||null;var y=m,B="undefined"!==
typeof OffscreenCanvas&&y instanceof OffscreenCanvas;if(!("undefined"!==typeof HTMLCanvasElement&&y instanceof HTMLCanvasElement||B||(y=document.getElementById(m),y)))throw"Canvas with id "+m+" was not found";m=this.GetWebGLContext(y,x);if(!m||0>m)throw"failed to create webgl context: err "+m;m=this.MakeWebGLContext(m);p=this.MakeOnScreenGLSurface(m,y.width,y.height,p);return p?p:(p=y.cloneNode(!0),y.parentNode.replaceChild(p,y),p.classList.add("ck-replaced"),a.MakeSWCanvasSurface(p))};a.MakeCanvasSurface=
a.MakeWebGLCanvasSurface;a.Surface.prototype.makeImageFromTexture=function(m,p){a.Yd(this.Xd);m=c(m);if(p=this._makeImageFromTexture(this.Xd,m,p))p.xe=m;return p};a.Surface.prototype.makeImageFromTextureSource=function(m,p,x){p||(p={height:d(m),width:f(m),colorType:a.ColorType.RGBA_8888,alphaType:x?a.AlphaType.Premul:a.AlphaType.Unpremul});p.colorSpace||(p.colorSpace=a.ColorSpace.SRGB);a.Yd(this.Xd);var y=v.ie;x=k(y,y.createTexture(),p,x);2===v.version?y.texImage2D(y.TEXTURE_2D,0,y.RGBA,p.width,p.height,
0,y.RGBA,y.UNSIGNED_BYTE,m):y.texImage2D(y.TEXTURE_2D,0,y.RGBA,y.RGBA,y.UNSIGNED_BYTE,m);l(y,p);this._resetContext();return this.makeImageFromTexture(x,p)};a.Surface.prototype.updateTextureFromSource=function(m,p,x){if(m.xe){a.Yd(this.Xd);var y=m.getImageInfo(),B=v.ie,D=k(B,ea[m.xe],y,x);2===v.version?B.texImage2D(B.TEXTURE_2D,0,B.RGBA,f(p),d(p),0,B.RGBA,B.UNSIGNED_BYTE,p):B.texImage2D(B.TEXTURE_2D,0,B.RGBA,B.RGBA,B.UNSIGNED_BYTE,p);l(B,y,x);this._resetContext();ea[m.xe]=null;m.xe=c(D);y.colorSpace=
m.getColorSpace();p=this._makeImageFromTexture(this.Xd,m.xe,y);x=m.zd.Zd;B=m.zd.de;m.zd.Zd=p.zd.Zd;m.zd.de=p.zd.de;p.zd.Zd=x;p.zd.de=B;p.delete();y.colorSpace.delete()}};a.MakeLazyImageFromTextureSource=function(m,p,x){p||(p={height:d(m),width:f(m),colorType:a.ColorType.RGBA_8888,alphaType:x?a.AlphaType.Premul:a.AlphaType.Unpremul});p.colorSpace||(p.colorSpace=a.ColorSpace.SRGB);var y={makeTexture:function(){var B=v,D=B.ie,u=k(D,D.createTexture(),p,x);2===B.version?D.texImage2D(D.TEXTURE_2D,0,D.RGBA,
p.width,p.height,0,D.RGBA,D.UNSIGNED_BYTE,m):D.texImage2D(D.TEXTURE_2D,0,D.RGBA,D.RGBA,D.UNSIGNED_BYTE,m);l(D,p,x);return c(u)},freeSrc:function(){}};"VideoFrame"===m.constructor.name&&(y.freeSrc=function(){m.close()});return a.Image._makeFromGenerator(p,y)};a.Yd=function(m){return m?ha(m):!1};a.De=function(){return v&&v.Pe&&!v.Pe.isDeleted()?v.Pe:null}})})(r);
(function(a){function b(g){return(f(255*g[3])<<24|f(255*g[0])<<16|f(255*g[1])<<8|f(255*g[2])<<0)>>>0}function c(g){if(g&&g._ck)return g;if(g instanceof Float32Array){for(var e=Math.floor(g.length/4),h=new Uint32Array(e),n=0;n<e;n++)h[n]=b(g.slice(4*n,4*(n+1)));return h}if(g instanceof Uint32Array)return g;if(g instanceof Array&&g[0]instanceof Float32Array)return g.map(b)}function d(g){if(void 0===g)return 1;var e=parseFloat(g);return g&&-1!==g.indexOf("%")?e/100:e}function f(g){return Math.round(Math.max(0,
Math.min(g||0,255)))}function k(g,e){e&&e._ck||a._free(g)}function l(g,e,h){if(!g||!g.length)return M;if(g&&g._ck)return g.byteOffset;var n=a[e].BYTES_PER_ELEMENT;h||(h=a._malloc(g.length*n));a[e].set(g,h/n);return h}function m(g){var e={fe:M,count:g.length,colorType:a.ColorType.RGBA_F32};if(g instanceof Float32Array)e.fe=l(g,"HEAPF32"),e.count=g.length/4;else if(g instanceof Uint32Array)e.fe=l(g,"HEAPU32"),e.colorType=a.ColorType.RGBA_8888;else if(g instanceof Array){if(g&&g.length){for(var h=a._malloc(16*
g.length),n=0,t=h/4,w=0;w<g.length;w++)for(var z=0;4>z;z++)a.HEAPF32[t+n]=g[w][z],n++;g=h}else g=M;e.fe=g}else throw"Invalid argument to copyFlexibleColorArray, Not a color array "+typeof g;return e}function p(g){if(!g)return M;var e=T.toTypedArray();if(g.length){if(6===g.length||9===g.length)return l(g,"HEAPF32",H),6===g.length&&a.HEAPF32.set(jd,6+H/4),H;if(16===g.length)return e[0]=g[0],e[1]=g[1],e[2]=g[3],e[3]=g[4],e[4]=g[5],e[5]=g[7],e[6]=g[12],e[7]=g[13],e[8]=g[15],H;throw"invalid matrix size";
}if(void 0===g.m11)throw"invalid matrix argument";e[0]=g.m11;e[1]=g.m21;e[2]=g.m41;e[3]=g.m12;e[4]=g.m22;e[5]=g.m42;e[6]=g.m14;e[7]=g.m24;e[8]=g.m44;return H}function x(g){if(!g)return M;var e=Y.toTypedArray();if(g.length){if(16!==g.length&&6!==g.length&&9!==g.length)throw"invalid matrix size";if(16===g.length)return l(g,"HEAPF32",ca);e.fill(0);e[0]=g[0];e[1]=g[1];e[3]=g[2];e[4]=g[3];e[5]=g[4];e[7]=g[5];e[10]=1;e[12]=g[6];e[13]=g[7];e[15]=g[8];6===g.length&&(e[12]=0,e[13]=0,e[15]=1);return ca}if(void 0===
g.m11)throw"invalid matrix argument";e[0]=g.m11;e[1]=g.m21;e[2]=g.m31;e[3]=g.m41;e[4]=g.m12;e[5]=g.m22;e[6]=g.m32;e[7]=g.m42;e[8]=g.m13;e[9]=g.m23;e[10]=g.m33;e[11]=g.m43;e[12]=g.m14;e[13]=g.m24;e[14]=g.m34;e[15]=g.m44;return ca}function y(g,e){return l(g,"HEAPF32",e||wa)}function B(g,e,h,n){var t=Pa.toTypedArray();t[0]=g;t[1]=e;t[2]=h;t[3]=n;return wa}function D(g){for(var e=new Float32Array(4),h=0;4>h;h++)e[h]=a.HEAPF32[g/4+h];return e}function u(g,e){return l(g,"HEAPF32",e||X)}function F(g,e){return l(g,
"HEAPF32",e||Fb)}a.Color=function(g,e,h,n){void 0===n&&(n=1);return a.Color4f(f(g)/255,f(e)/255,f(h)/255,n)};a.ColorAsInt=function(g,e,h,n){void 0===n&&(n=255);return(f(n)<<24|f(g)<<16|f(e)<<8|f(h)<<0&268435455)>>>0};a.Color4f=function(g,e,h,n){void 0===n&&(n=1);return Float32Array.of(g,e,h,n)};Object.defineProperty(a,"TRANSPARENT",{get:function(){return a.Color4f(0,0,0,0)}});Object.defineProperty(a,"BLACK",{get:function(){return a.Color4f(0,0,0,1)}});Object.defineProperty(a,"WHITE",{get:function(){return a.Color4f(1,
1,1,1)}});Object.defineProperty(a,"RED",{get:function(){return a.Color4f(1,0,0,1)}});Object.defineProperty(a,"GREEN",{get:function(){return a.Color4f(0,1,0,1)}});Object.defineProperty(a,"BLUE",{get:function(){return a.Color4f(0,0,1,1)}});Object.defineProperty(a,"YELLOW",{get:function(){return a.Color4f(1,1,0,1)}});Object.defineProperty(a,"CYAN",{get:function(){return a.Color4f(0,1,1,1)}});Object.defineProperty(a,"MAGENTA",{get:function(){return a.Color4f(1,0,1,1)}});a.getColorComponents=function(g){return[Math.floor(255*
g[0]),Math.floor(255*g[1]),Math.floor(255*g[2]),g[3]]};a.parseColorString=function(g,e){g=g.toLowerCase();if(g.startsWith("#")){e=255;switch(g.length){case 9:e=parseInt(g.slice(7,9),16);case 7:var h=parseInt(g.slice(1,3),16);var n=parseInt(g.slice(3,5),16);var t=parseInt(g.slice(5,7),16);break;case 5:e=17*parseInt(g.slice(4,5),16);case 4:h=17*parseInt(g.slice(1,2),16),n=17*parseInt(g.slice(2,3),16),t=17*parseInt(g.slice(3,4),16)}return a.Color(h,n,t,e/255)}return g.startsWith("rgba")?(g=g.slice(5,
-1),g=g.split(","),a.Color(+g[0],+g[1],+g[2],d(g[3]))):g.startsWith("rgb")?(g=g.slice(4,-1),g=g.split(","),a.Color(+g[0],+g[1],+g[2],d(g[3]))):g.startsWith("gray(")||g.startsWith("hsl")||!e||(g=e[g],void 0===g)?a.BLACK:g};a.multiplyByAlpha=function(g,e){g=g.slice();g[3]=Math.max(0,Math.min(g[3]*e,1));return g};a.Malloc=function(g,e){var h=a._malloc(e*g.BYTES_PER_ELEMENT);return{_ck:!0,length:e,byteOffset:h,qe:null,subarray:function(n,t){n=this.toTypedArray().subarray(n,t);n._ck=!0;return n},toTypedArray:function(){if(this.qe&&
this.qe.length)return this.qe;this.qe=new g(a.HEAPU8.buffer,h,e);this.qe._ck=!0;return this.qe}}};a.Free=function(g){a._free(g.byteOffset);g.byteOffset=M;g.toTypedArray=null;g.qe=null};var H=M,T,ca=M,Y,wa=M,Pa,oa,X=M,gc,Ca=M,hc,Gb=M,ic,Hb=M,ib,Ta=M,jc,Fb=M,kc,lc=M,jd=Float32Array.of(0,0,1),M=0;a.onRuntimeInitialized=function(){function g(e,h,n,t,w,z,E){z||(z=4*t.width,t.colorType===a.ColorType.RGBA_F16?z*=2:t.colorType===a.ColorType.RGBA_F32&&(z*=4));var K=z*t.height;var I=w?w.byteOffset:a._malloc(K);
if(E?!e._readPixels(t,I,z,h,n,E):!e._readPixels(t,I,z,h,n))return w||a._free(I),null;if(w)return w.toTypedArray();switch(t.colorType){case a.ColorType.RGBA_8888:case a.ColorType.RGBA_F16:e=(new Uint8Array(a.HEAPU8.buffer,I,K)).slice();break;case a.ColorType.RGBA_F32:e=(new Float32Array(a.HEAPU8.buffer,I,K)).slice();break;default:return null}a._free(I);return e}Pa=a.Malloc(Float32Array,4);wa=Pa.byteOffset;Y=a.Malloc(Float32Array,16);ca=Y.byteOffset;T=a.Malloc(Float32Array,9);H=T.byteOffset;jc=a.Malloc(Float32Array,
12);Fb=jc.byteOffset;kc=a.Malloc(Float32Array,12);lc=kc.byteOffset;oa=a.Malloc(Float32Array,4);X=oa.byteOffset;gc=a.Malloc(Float32Array,4);Ca=gc.byteOffset;hc=a.Malloc(Float32Array,3);Gb=hc.byteOffset;ic=a.Malloc(Float32Array,3);Hb=ic.byteOffset;ib=a.Malloc(Int32Array,4);Ta=ib.byteOffset;a.ColorSpace.SRGB=a.ColorSpace._MakeSRGB();a.ColorSpace.DISPLAY_P3=a.ColorSpace._MakeDisplayP3();a.ColorSpace.ADOBE_RGB=a.ColorSpace._MakeAdobeRGB();a.GlyphRunFlags={IsWhiteSpace:a._GlyphRunFlags_isWhiteSpace};a.Path.MakeFromCmds=
function(e){var h=l(e,"HEAPF32"),n=a.Path._MakeFromCmds(h,e.length);k(h,e);return n};a.Path.MakeFromVerbsPointsWeights=function(e,h,n){var t=l(e,"HEAPU8"),w=l(h,"HEAPF32"),z=l(n,"HEAPF32"),E=a.Path._MakeFromVerbsPointsWeights(t,e.length,w,h.length,z,n&&n.length||0);k(t,e);k(w,h);k(z,n);return E};a.Path.prototype.addArc=function(e,h,n){e=u(e);this._addArc(e,h,n);return this};a.Path.prototype.addCircle=function(e,h,n,t){this._addCircle(e,h,n,!!t);return this};a.Path.prototype.addOval=function(e,h,n){void 0===
n&&(n=1);e=u(e);this._addOval(e,!!h,n);return this};a.Path.prototype.addPath=function(){var e=Array.prototype.slice.call(arguments),h=e[0],n=!1;"boolean"===typeof e[e.length-1]&&(n=e.pop());if(1===e.length)this._addPath(h,1,0,0,0,1,0,0,0,1,n);else if(2===e.length)e=e[1],this._addPath(h,e[0],e[1],e[2],e[3],e[4],e[5],e[6]||0,e[7]||0,e[8]||1,n);else if(7===e.length||10===e.length)this._addPath(h,e[1],e[2],e[3],e[4],e[5],e[6],e[7]||0,e[8]||0,e[9]||1,n);else return null;return this};a.Path.prototype.addPoly=
function(e,h){var n=l(e,"HEAPF32");this._addPoly(n,e.length/2,h);k(n,e);return this};a.Path.prototype.addRect=function(e,h){e=u(e);this._addRect(e,!!h);return this};a.Path.prototype.addRRect=function(e,h){e=F(e);this._addRRect(e,!!h);return this};a.Path.prototype.addVerbsPointsWeights=function(e,h,n){var t=l(e,"HEAPU8"),w=l(h,"HEAPF32"),z=l(n,"HEAPF32");this._addVerbsPointsWeights(t,e.length,w,h.length,z,n&&n.length||0);k(t,e);k(w,h);k(z,n)};a.Path.prototype.arc=function(e,h,n,t,w,z){e=a.LTRBRect(e-
n,h-n,e+n,h+n);w=(w-t)/Math.PI*180-360*!!z;z=new a.Path;z.addArc(e,t/Math.PI*180,w);this.addPath(z,!0);z.delete();return this};a.Path.prototype.arcToOval=function(e,h,n,t){e=u(e);this._arcToOval(e,h,n,t);return this};a.Path.prototype.arcToRotated=function(e,h,n,t,w,z,E){this._arcToRotated(e,h,n,!!t,!!w,z,E);return this};a.Path.prototype.arcToTangent=function(e,h,n,t,w){this._arcToTangent(e,h,n,t,w);return this};a.Path.prototype.close=function(){this._close();return this};a.Path.prototype.conicTo=
function(e,h,n,t,w){this._conicTo(e,h,n,t,w);return this};a.Path.prototype.computeTightBounds=function(e){this._computeTightBounds(X);var h=oa.toTypedArray();return e?(e.set(h),e):h.slice()};a.Path.prototype.cubicTo=function(e,h,n,t,w,z){this._cubicTo(e,h,n,t,w,z);return this};a.Path.prototype.dash=function(e,h,n){return this._dash(e,h,n)?this:null};a.Path.prototype.getBounds=function(e){this._getBounds(X);var h=oa.toTypedArray();return e?(e.set(h),e):h.slice()};a.Path.prototype.lineTo=function(e,
h){this._lineTo(e,h);return this};a.Path.prototype.moveTo=function(e,h){this._moveTo(e,h);return this};a.Path.prototype.offset=function(e,h){this._transform(1,0,e,0,1,h,0,0,1);return this};a.Path.prototype.quadTo=function(e,h,n,t){this._quadTo(e,h,n,t);return this};a.Path.prototype.rArcTo=function(e,h,n,t,w,z,E){this._rArcTo(e,h,n,t,w,z,E);return this};a.Path.prototype.rConicTo=function(e,h,n,t,w){this._rConicTo(e,h,n,t,w);return this};a.Path.prototype.rCubicTo=function(e,h,n,t,w,z){this._rCubicTo(e,
h,n,t,w,z);return this};a.Path.prototype.rLineTo=function(e,h){this._rLineTo(e,h);return this};a.Path.prototype.rMoveTo=function(e,h){this._rMoveTo(e,h);return this};a.Path.prototype.rQuadTo=function(e,h,n,t){this._rQuadTo(e,h,n,t);return this};a.Path.prototype.stroke=function(e){e=e||{};e.width=e.width||1;e.miter_limit=e.miter_limit||4;e.cap=e.cap||a.StrokeCap.Butt;e.join=e.join||a.StrokeJoin.Miter;e.precision=e.precision||1;return this._stroke(e)?this:null};a.Path.prototype.transform=function(){if(1===
arguments.length){var e=arguments[0];this._transform(e[0],e[1],e[2],e[3],e[4],e[5],e[6]||0,e[7]||0,e[8]||1)}else if(6===arguments.length||9===arguments.length)e=arguments,this._transform(e[0],e[1],e[2],e[3],e[4],e[5],e[6]||0,e[7]||0,e[8]||1);else throw"transform expected to take 1 or 9 arguments. Got "+arguments.length;return this};a.Path.prototype.trim=function(e,h,n){return this._trim(e,h,!!n)?this:null};a.Image.prototype.encodeToBytes=function(e,h){var n=a.De();e=e||a.ImageFormat.PNG;h=h||100;
return n?this._encodeToBytes(e,h,n):this._encodeToBytes(e,h)};a.Image.prototype.makeShaderCubic=function(e,h,n,t,w){w=p(w);return this._makeShaderCubic(e,h,n,t,w)};a.Image.prototype.makeShaderOptions=function(e,h,n,t,w){w=p(w);return this._makeShaderOptions(e,h,n,t,w)};a.Image.prototype.readPixels=function(e,h,n,t,w){var z=a.De();return g(this,e,h,n,t,w,z)};a.Canvas.prototype.clear=function(e){a.Yd(this.Xd);e=y(e);this._clear(e)};a.Canvas.prototype.clipRRect=function(e,h,n){a.Yd(this.Xd);e=F(e);this._clipRRect(e,
h,n)};a.Canvas.prototype.clipRect=function(e,h,n){a.Yd(this.Xd);e=u(e);this._clipRect(e,h,n)};a.Canvas.prototype.concat=function(e){a.Yd(this.Xd);e=x(e);this._concat(e)};a.Canvas.prototype.drawArc=function(e,h,n,t,w){a.Yd(this.Xd);e=u(e);this._drawArc(e,h,n,t,w)};a.Canvas.prototype.drawAtlas=function(e,h,n,t,w,z,E){if(e&&t&&h&&n&&h.length===n.length){a.Yd(this.Xd);w||(w=a.BlendMode.SrcOver);var K=l(h,"HEAPF32"),I=l(n,"HEAPF32"),U=n.length/4,V=l(c(z),"HEAPU32");if(E&&"B"in E&&"C"in E)this._drawAtlasCubic(e,
I,K,V,U,w,E.B,E.C,t);else{let q=a.FilterMode.Linear,A=a.MipmapMode.None;E&&(q=E.filter,"mipmap"in E&&(A=E.mipmap));this._drawAtlasOptions(e,I,K,V,U,w,q,A,t)}k(K,h);k(I,n);k(V,z)}};a.Canvas.prototype.drawCircle=function(e,h,n,t){a.Yd(this.Xd);this._drawCircle(e,h,n,t)};a.Canvas.prototype.drawColor=function(e,h){a.Yd(this.Xd);e=y(e);void 0!==h?this._drawColor(e,h):this._drawColor(e)};a.Canvas.prototype.drawColorInt=function(e,h){a.Yd(this.Xd);this._drawColorInt(e,h||a.BlendMode.SrcOver)};a.Canvas.prototype.drawColorComponents=
function(e,h,n,t,w){a.Yd(this.Xd);e=B(e,h,n,t);void 0!==w?this._drawColor(e,w):this._drawColor(e)};a.Canvas.prototype.drawDRRect=function(e,h,n){a.Yd(this.Xd);e=F(e,Fb);h=F(h,lc);this._drawDRRect(e,h,n)};a.Canvas.prototype.drawImage=function(e,h,n,t){a.Yd(this.Xd);this._drawImage(e,h,n,t||null)};a.Canvas.prototype.drawImageCubic=function(e,h,n,t,w,z){a.Yd(this.Xd);this._drawImageCubic(e,h,n,t,w,z||null)};a.Canvas.prototype.drawImageOptions=function(e,h,n,t,w,z){a.Yd(this.Xd);this._drawImageOptions(e,
h,n,t,w,z||null)};a.Canvas.prototype.drawImageNine=function(e,h,n,t,w){a.Yd(this.Xd);h=l(h,"HEAP32",Ta);n=u(n);this._drawImageNine(e,h,n,t,w||null)};a.Canvas.prototype.drawImageRect=function(e,h,n,t,w){a.Yd(this.Xd);u(h,X);u(n,Ca);this._drawImageRect(e,X,Ca,t,!!w)};a.Canvas.prototype.drawImageRectCubic=function(e,h,n,t,w,z){a.Yd(this.Xd);u(h,X);u(n,Ca);this._drawImageRectCubic(e,X,Ca,t,w,z||null)};a.Canvas.prototype.drawImageRectOptions=function(e,h,n,t,w,z){a.Yd(this.Xd);u(h,X);u(n,Ca);this._drawImageRectOptions(e,
X,Ca,t,w,z||null)};a.Canvas.prototype.drawLine=function(e,h,n,t,w){a.Yd(this.Xd);this._drawLine(e,h,n,t,w)};a.Canvas.prototype.drawOval=function(e,h){a.Yd(this.Xd);e=u(e);this._drawOval(e,h)};a.Canvas.prototype.drawPaint=function(e){a.Yd(this.Xd);this._drawPaint(e)};a.Canvas.prototype.drawParagraph=function(e,h,n){a.Yd(this.Xd);this._drawParagraph(e,h,n)};a.Canvas.prototype.drawPatch=function(e,h,n,t,w){if(24>e.length)throw"Need 12 cubic points";if(h&&4>h.length)throw"Need 4 colors";if(n&&8>n.length)throw"Need 4 shader coordinates";
a.Yd(this.Xd);const z=l(e,"HEAPF32"),E=h?l(c(h),"HEAPU32"):M,K=n?l(n,"HEAPF32"):M;t||(t=a.BlendMode.Modulate);this._drawPatch(z,E,K,t,w);k(K,n);k(E,h);k(z,e)};a.Canvas.prototype.drawPath=function(e,h){a.Yd(this.Xd);this._drawPath(e,h)};a.Canvas.prototype.drawPicture=function(e){a.Yd(this.Xd);this._drawPicture(e)};a.Canvas.prototype.drawPoints=function(e,h,n){a.Yd(this.Xd);var t=l(h,"HEAPF32");this._drawPoints(e,t,h.length/2,n);k(t,h)};a.Canvas.prototype.drawRRect=function(e,h){a.Yd(this.Xd);e=F(e);
this._drawRRect(e,h)};a.Canvas.prototype.drawRect=function(e,h){a.Yd(this.Xd);e=u(e);this._drawRect(e,h)};a.Canvas.prototype.drawRect4f=function(e,h,n,t,w){a.Yd(this.Xd);this._drawRect4f(e,h,n,t,w)};a.Canvas.prototype.drawShadow=function(e,h,n,t,w,z,E){a.Yd(this.Xd);var K=l(w,"HEAPF32"),I=l(z,"HEAPF32");h=l(h,"HEAPF32",Gb);n=l(n,"HEAPF32",Hb);this._drawShadow(e,h,n,t,K,I,E);k(K,w);k(I,z)};a.getShadowLocalBounds=function(e,h,n,t,w,z,E){e=p(e);n=l(n,"HEAPF32",Gb);t=l(t,"HEAPF32",Hb);if(!this._getShadowLocalBounds(e,
h,n,t,w,z,X))return null;h=oa.toTypedArray();return E?(E.set(h),E):h.slice()};a.Canvas.prototype.drawTextBlob=function(e,h,n,t){a.Yd(this.Xd);this._drawTextBlob(e,h,n,t)};a.Canvas.prototype.drawVertices=function(e,h,n){a.Yd(this.Xd);this._drawVertices(e,h,n)};a.Canvas.prototype.getDeviceClipBounds=function(e){this._getDeviceClipBounds(Ta);var h=ib.toTypedArray();e?e.set(h):e=h.slice();return e};a.Canvas.prototype.quickReject=function(e){e=u(e);return this._quickReject(e)};a.Canvas.prototype.getLocalToDevice=
function(){this._getLocalToDevice(ca);for(var e=ca,h=Array(16),n=0;16>n;n++)h[n]=a.HEAPF32[e/4+n];return h};a.Canvas.prototype.getTotalMatrix=function(){this._getTotalMatrix(H);for(var e=Array(9),h=0;9>h;h++)e[h]=a.HEAPF32[H/4+h];return e};a.Canvas.prototype.makeSurface=function(e){e=this._makeSurface(e);e.Xd=this.Xd;return e};a.Canvas.prototype.readPixels=function(e,h,n,t,w){a.Yd(this.Xd);return g(this,e,h,n,t,w)};a.Canvas.prototype.saveLayer=function(e,h,n,t,w){h=u(h);return this._saveLayer(e||
null,h,n||null,t||0,w||a.TileMode.Clamp)};a.Canvas.prototype.writePixels=function(e,h,n,t,w,z,E,K){if(e.byteLength%(h*n))throw"pixels length must be a multiple of the srcWidth * srcHeight";a.Yd(this.Xd);var I=e.byteLength/(h*n);z=z||a.AlphaType.Unpremul;E=E||a.ColorType.RGBA_8888;K=K||a.ColorSpace.SRGB;var U=I*h;I=l(e,"HEAPU8");h=this._writePixels({width:h,height:n,colorType:E,alphaType:z,colorSpace:K},I,U,t,w);k(I,e);return h};a.ColorFilter.MakeBlend=function(e,h,n){e=y(e);n=n||a.ColorSpace.SRGB;
return a.ColorFilter._MakeBlend(e,h,n)};a.ColorFilter.MakeMatrix=function(e){if(!e||20!==e.length)throw"invalid color matrix";var h=l(e,"HEAPF32"),n=a.ColorFilter._makeMatrix(h);k(h,e);return n};a.ContourMeasure.prototype.getPosTan=function(e,h){this._getPosTan(e,X);e=oa.toTypedArray();return h?(h.set(e),h):e.slice()};a.ImageFilter.prototype.getOutputBounds=function(e,h,n){e=u(e,X);h=p(h);this._getOutputBounds(e,h,Ta);h=ib.toTypedArray();return n?(n.set(h),n):h.slice()};a.ImageFilter.MakeDropShadow=
function(e,h,n,t,w,z){w=y(w,wa);return a.ImageFilter._MakeDropShadow(e,h,n,t,w,z)};a.ImageFilter.MakeDropShadowOnly=function(e,h,n,t,w,z){w=y(w,wa);return a.ImageFilter._MakeDropShadowOnly(e,h,n,t,w,z)};a.ImageFilter.MakeImage=function(e,h,n,t){n=u(n,X);t=u(t,Ca);if("B"in h&&"C"in h)return a.ImageFilter._MakeImageCubic(e,h.B,h.C,n,t);const w=h.filter;let z=a.MipmapMode.None;"mipmap"in h&&(z=h.mipmap);return a.ImageFilter._MakeImageOptions(e,w,z,n,t)};a.ImageFilter.MakeMatrixTransform=function(e,h,
n){e=p(e);if("B"in h&&"C"in h)return a.ImageFilter._MakeMatrixTransformCubic(e,h.B,h.C,n);const t=h.filter;let w=a.MipmapMode.None;"mipmap"in h&&(w=h.mipmap);return a.ImageFilter._MakeMatrixTransformOptions(e,t,w,n)};a.Paint.prototype.getColor=function(){this._getColor(wa);return D(wa)};a.Paint.prototype.setColor=function(e,h){h=h||null;e=y(e);this._setColor(e,h)};a.Paint.prototype.setColorComponents=function(e,h,n,t,w){w=w||null;e=B(e,h,n,t);this._setColor(e,w)};a.Path.prototype.getPoint=function(e,
h){this._getPoint(e,X);e=oa.toTypedArray();return h?(h[0]=e[0],h[1]=e[1],h):e.slice(0,2)};a.Picture.prototype.makeShader=function(e,h,n,t,w){t=p(t);w=u(w);return this._makeShader(e,h,n,t,w)};a.Picture.prototype.cullRect=function(e){this._cullRect(X);var h=oa.toTypedArray();return e?(e.set(h),e):h.slice()};a.PictureRecorder.prototype.beginRecording=function(e,h){e=u(e);return this._beginRecording(e,!!h)};a.Surface.prototype.getCanvas=function(){var e=this._getCanvas();e.Xd=this.Xd;return e};a.Surface.prototype.makeImageSnapshot=
function(e){a.Yd(this.Xd);e=l(e,"HEAP32",Ta);return this._makeImageSnapshot(e)};a.Surface.prototype.makeSurface=function(e){a.Yd(this.Xd);e=this._makeSurface(e);e.Xd=this.Xd;return e};a.Surface.prototype.hf=function(e,h){this.we||(this.we=this.getCanvas());return requestAnimationFrame(function(){a.Yd(this.Xd);e(this.we);this.flush(h)}.bind(this))};a.Surface.prototype.requestAnimationFrame||(a.Surface.prototype.requestAnimationFrame=a.Surface.prototype.hf);a.Surface.prototype.ef=function(e,h){this.we||
(this.we=this.getCanvas());requestAnimationFrame(function(){a.Yd(this.Xd);e(this.we);this.flush(h);this.dispose()}.bind(this))};a.Surface.prototype.drawOnce||(a.Surface.prototype.drawOnce=a.Surface.prototype.ef);a.PathEffect.MakeDash=function(e,h){h||(h=0);if(!e.length||1===e.length%2)throw"Intervals array must have even length";var n=l(e,"HEAPF32");h=a.PathEffect._MakeDash(n,e.length,h);k(n,e);return h};a.PathEffect.MakeLine2D=function(e,h){h=p(h);return a.PathEffect._MakeLine2D(e,h)};a.PathEffect.MakePath2D=
function(e,h){e=p(e);return a.PathEffect._MakePath2D(e,h)};a.Shader.MakeColor=function(e,h){h=h||null;e=y(e);return a.Shader._MakeColor(e,h)};a.Shader.Blend=a.Shader.MakeBlend;a.Shader.Color=a.Shader.MakeColor;a.Shader.MakeLinearGradient=function(e,h,n,t,w,z,E,K){K=K||null;var I=m(n),U=l(t,"HEAPF32");E=E||0;z=p(z);var V=oa.toTypedArray();V.set(e);V.set(h,2);e=a.Shader._MakeLinearGradient(X,I.fe,I.colorType,U,I.count,w,E,z,K);k(I.fe,n);t&&k(U,t);return e};a.Shader.MakeRadialGradient=function(e,h,n,
t,w,z,E,K){K=K||null;var I=m(n),U=l(t,"HEAPF32");E=E||0;z=p(z);e=a.Shader._MakeRadialGradient(e[0],e[1],h,I.fe,I.colorType,U,I.count,w,E,z,K);k(I.fe,n);t&&k(U,t);return e};a.Shader.MakeSweepGradient=function(e,h,n,t,w,z,E,K,I,U){U=U||null;var V=m(n),q=l(t,"HEAPF32");E=E||0;K=K||0;I=I||360;z=p(z);e=a.Shader._MakeSweepGradient(e,h,V.fe,V.colorType,q,V.count,w,K,I,E,z,U);k(V.fe,n);t&&k(q,t);return e};a.Shader.MakeTwoPointConicalGradient=function(e,h,n,t,w,z,E,K,I,U){U=U||null;var V=m(w),q=l(z,"HEAPF32");
I=I||0;K=p(K);var A=oa.toTypedArray();A.set(e);A.set(n,2);e=a.Shader._MakeTwoPointConicalGradient(X,h,t,V.fe,V.colorType,q,V.count,E,I,K,U);k(V.fe,w);z&&k(q,z);return e};a.Vertices.prototype.bounds=function(e){this._bounds(X);var h=oa.toTypedArray();return e?(e.set(h),e):h.slice()};a.ae&&a.ae.forEach(function(e){e()})};a.computeTonalColors=function(g){var e=l(g.ambient,"HEAPF32"),h=l(g.spot,"HEAPF32");this._computeTonalColors(e,h);var n={ambient:D(e),spot:D(h)};k(e,g.ambient);k(h,g.spot);return n};
a.LTRBRect=function(g,e,h,n){return Float32Array.of(g,e,h,n)};a.XYWHRect=function(g,e,h,n){return Float32Array.of(g,e,g+h,e+n)};a.LTRBiRect=function(g,e,h,n){return Int32Array.of(g,e,h,n)};a.XYWHiRect=function(g,e,h,n){return Int32Array.of(g,e,g+h,e+n)};a.RRectXY=function(g,e,h){return Float32Array.of(g[0],g[1],g[2],g[3],e,h,e,h,e,h,e,h)};a.MakeAnimatedImageFromEncoded=function(g){g=new Uint8Array(g);var e=a._malloc(g.byteLength);a.HEAPU8.set(g,e);return(g=a._decodeAnimatedImage(e,g.byteLength))?
g:null};a.MakeImageFromEncoded=function(g){g=new Uint8Array(g);var e=a._malloc(g.byteLength);a.HEAPU8.set(g,e);return(g=a._decodeImage(e,g.byteLength))?g:null};var Ua=null;a.MakeImageFromCanvasImageSource=function(g){var e=g.width,h=g.height;Ua||(Ua=document.createElement("canvas"));Ua.width=e;Ua.height=h;var n=Ua.getContext("2d",{willReadFrequently:!0});n.drawImage(g,0,0);g=n.getImageData(0,0,e,h);return a.MakeImage({width:e,height:h,alphaType:a.AlphaType.Unpremul,colorType:a.ColorType.RGBA_8888,
colorSpace:a.ColorSpace.SRGB},g.data,4*e)};a.MakeImage=function(g,e,h){var n=a._malloc(e.length);a.HEAPU8.set(e,n);return a._MakeImage(g,n,e.length,h)};a.MakeVertices=function(g,e,h,n,t,w){var z=t&&t.length||0,E=0;h&&h.length&&(E|=1);n&&n.length&&(E|=2);void 0===w||w||(E|=4);g=new a._VerticesBuilder(g,e.length/2,z,E);l(e,"HEAPF32",g.positions());g.texCoords()&&l(h,"HEAPF32",g.texCoords());g.colors()&&l(c(n),"HEAPU32",g.colors());g.indices()&&l(t,"HEAPU16",g.indices());return g.detach()};(function(g){g.ae=
g.ae||[];g.ae.push(function(){function e(q){q&&(q.dir=0===q.dir?g.TextDirection.RTL:g.TextDirection.LTR);return q}function h(q){if(!q||!q.length)return[];for(var A=[],Q=0;Q<q.length;Q+=5){var Z=g.LTRBRect(q[Q],q[Q+1],q[Q+2],q[Q+3]),Aa=g.TextDirection.LTR;0===q[Q+4]&&(Aa=g.TextDirection.RTL);A.push({rect:Z,dir:Aa})}g._free(q.byteOffset);return A}function n(q){q=q||{};void 0===q.weight&&(q.weight=g.FontWeight.Normal);q.width=q.width||g.FontWidth.Normal;q.slant=q.slant||g.FontSlant.Upright;return q}
function t(q){if(!q||!q.length)return M;for(var A=[],Q=0;Q<q.length;Q++){var Z=w(q[Q]);A.push(Z)}return l(A,"HEAPU32")}function w(q){if(K[q])return K[q];var A=ja(q)+1,Q=g._malloc(A);ka(q,C,Q,A);return K[q]=Q}function z(q){q._colorPtr=y(q.color);q._foregroundColorPtr=M;q._backgroundColorPtr=M;q._decorationColorPtr=M;q.foregroundColor&&(q._foregroundColorPtr=y(q.foregroundColor,I));q.backgroundColor&&(q._backgroundColorPtr=y(q.backgroundColor,U));q.decorationColor&&(q._decorationColorPtr=y(q.decorationColor,
V));Array.isArray(q.fontFamilies)&&q.fontFamilies.length?(q._fontFamiliesPtr=t(q.fontFamilies),q._fontFamiliesLen=q.fontFamilies.length):(q._fontFamiliesPtr=M,q._fontFamiliesLen=0);if(q.locale){var A=q.locale;q._localePtr=w(A);q._localeLen=ja(A)}else q._localePtr=M,q._localeLen=0;if(Array.isArray(q.shadows)&&q.shadows.length){A=q.shadows;var Q=A.map(function(ra){return ra.color||g.BLACK}),Z=A.map(function(ra){return ra.blurRadius||0});q._shadowLen=A.length;for(var Aa=g._malloc(8*A.length),Ib=Aa/4,
Jb=0;Jb<A.length;Jb++){var mc=A[Jb].offset||[0,0];g.HEAPF32[Ib]=mc[0];g.HEAPF32[Ib+1]=mc[1];Ib+=2}q._shadowColorsPtr=m(Q).fe;q._shadowOffsetsPtr=Aa;q._shadowBlurRadiiPtr=l(Z,"HEAPF32")}else q._shadowLen=0,q._shadowColorsPtr=M,q._shadowOffsetsPtr=M,q._shadowBlurRadiiPtr=M;Array.isArray(q.fontFeatures)&&q.fontFeatures.length?(A=q.fontFeatures,Q=A.map(function(ra){return ra.name}),Z=A.map(function(ra){return ra.value}),q._fontFeatureLen=A.length,q._fontFeatureNamesPtr=t(Q),q._fontFeatureValuesPtr=l(Z,
"HEAPU32")):(q._fontFeatureLen=0,q._fontFeatureNamesPtr=M,q._fontFeatureValuesPtr=M);Array.isArray(q.fontVariations)&&q.fontVariations.length?(A=q.fontVariations,Q=A.map(function(ra){return ra.axis}),Z=A.map(function(ra){return ra.value}),q._fontVariationLen=A.length,q._fontVariationAxesPtr=t(Q),q._fontVariationValuesPtr=l(Z,"HEAPF32")):(q._fontVariationLen=0,q._fontVariationAxesPtr=M,q._fontVariationValuesPtr=M)}function E(q){g._free(q._fontFamiliesPtr);g._free(q._shadowColorsPtr);g._free(q._shadowOffsetsPtr);
g._free(q._shadowBlurRadiiPtr);g._free(q._fontFeatureNamesPtr);g._free(q._fontFeatureValuesPtr);g._free(q._fontVariationAxesPtr);g._free(q._fontVariationValuesPtr)}g.Paragraph.prototype.getRectsForRange=function(q,A,Q,Z){q=this._getRectsForRange(q,A,Q,Z);return h(q)};g.Paragraph.prototype.getRectsForPlaceholders=function(){var q=this._getRectsForPlaceholders();return h(q)};g.Paragraph.prototype.getGlyphInfoAt=function(q){return e(this._getGlyphInfoAt(q))};g.Paragraph.prototype.getClosestGlyphInfoAtCoordinate=
function(q,A){return e(this._getClosestGlyphInfoAtCoordinate(q,A))};g.TypefaceFontProvider.prototype.registerFont=function(q,A){q=g.Typeface.MakeTypefaceFromData(q);if(!q)return null;A=w(A);this._registerFont(q,A)};g.ParagraphStyle=function(q){q.disableHinting=q.disableHinting||!1;if(q.ellipsis){var A=q.ellipsis;q._ellipsisPtr=w(A);q._ellipsisLen=ja(A)}else q._ellipsisPtr=M,q._ellipsisLen=0;null==q.heightMultiplier&&(q.heightMultiplier=-1);q.maxLines=q.maxLines||0;q.replaceTabCharacters=q.replaceTabCharacters||
!1;A=(A=q.strutStyle)||{};A.strutEnabled=A.strutEnabled||!1;A.strutEnabled&&Array.isArray(A.fontFamilies)&&A.fontFamilies.length?(A._fontFamiliesPtr=t(A.fontFamilies),A._fontFamiliesLen=A.fontFamilies.length):(A._fontFamiliesPtr=M,A._fontFamiliesLen=0);A.fontStyle=n(A.fontStyle);null==A.fontSize&&(A.fontSize=-1);null==A.heightMultiplier&&(A.heightMultiplier=-1);A.halfLeading=A.halfLeading||!1;A.leading=A.leading||0;A.forceStrutHeight=A.forceStrutHeight||!1;q.strutStyle=A;q.textAlign=q.textAlign||
g.TextAlign.Start;q.textDirection=q.textDirection||g.TextDirection.LTR;q.textHeightBehavior=q.textHeightBehavior||g.TextHeightBehavior.All;q.textStyle=g.TextStyle(q.textStyle);q.applyRoundingHack=!1!==q.applyRoundingHack;return q};g.TextStyle=function(q){q.color||(q.color=g.BLACK);q.decoration=q.decoration||0;q.decorationThickness=q.decorationThickness||0;q.decorationStyle=q.decorationStyle||g.DecorationStyle.Solid;q.textBaseline=q.textBaseline||g.TextBaseline.Alphabetic;null==q.fontSize&&(q.fontSize=
-1);q.letterSpacing=q.letterSpacing||0;q.wordSpacing=q.wordSpacing||0;null==q.heightMultiplier&&(q.heightMultiplier=-1);q.halfLeading=q.halfLeading||!1;q.fontStyle=n(q.fontStyle);return q};var K={},I=g._malloc(16),U=g._malloc(16),V=g._malloc(16);g.ParagraphBuilder.Make=function(q,A){z(q.textStyle);A=g.ParagraphBuilder._Make(q,A);E(q.textStyle);return A};g.ParagraphBuilder.MakeFromFontProvider=function(q,A){z(q.textStyle);A=g.ParagraphBuilder._MakeFromFontProvider(q,A);E(q.textStyle);return A};g.ParagraphBuilder.MakeFromFontCollection=
function(q,A){z(q.textStyle);A=g.ParagraphBuilder._MakeFromFontCollection(q,A);E(q.textStyle);return A};g.ParagraphBuilder.ShapeText=function(q,A,Q){let Z=0;for(const Aa of A)Z+=Aa.length;if(Z!==q.length)throw"Accumulated block lengths must equal text.length";return g.ParagraphBuilder._ShapeText(q,A,Q)};g.ParagraphBuilder.prototype.pushStyle=function(q){z(q);this._pushStyle(q);E(q)};g.ParagraphBuilder.prototype.pushPaintStyle=function(q,A,Q){z(q);this._pushPaintStyle(q,A,Q);E(q)};g.ParagraphBuilder.prototype.addPlaceholder=
function(q,A,Q,Z,Aa){Q=Q||g.PlaceholderAlignment.Baseline;Z=Z||g.TextBaseline.Alphabetic;this._addPlaceholder(q||0,A||0,Q,Z,Aa||0)};g.ParagraphBuilder.prototype.setWordsUtf8=function(q){var A=l(q,"HEAPU32");this._setWordsUtf8(A,q&&q.length||0);k(A,q)};g.ParagraphBuilder.prototype.setWordsUtf16=function(q){var A=l(q,"HEAPU32");this._setWordsUtf16(A,q&&q.length||0);k(A,q)};g.ParagraphBuilder.prototype.setGraphemeBreaksUtf8=function(q){var A=l(q,"HEAPU32");this._setGraphemeBreaksUtf8(A,q&&q.length||
0);k(A,q)};g.ParagraphBuilder.prototype.setGraphemeBreaksUtf16=function(q){var A=l(q,"HEAPU32");this._setGraphemeBreaksUtf16(A,q&&q.length||0);k(A,q)};g.ParagraphBuilder.prototype.setLineBreaksUtf8=function(q){var A=l(q,"HEAPU32");this._setLineBreaksUtf8(A,q&&q.length||0);k(A,q)};g.ParagraphBuilder.prototype.setLineBreaksUtf16=function(q){var A=l(q,"HEAPU32");this._setLineBreaksUtf16(A,q&&q.length||0);k(A,q)}})})(r);a.ae=a.ae||[];a.ae.push(function(){a.Path.prototype.op=function(g,e){return this._op(g,
e)?this:null};a.Path.prototype.simplify=function(){return this._simplify()?this:null}});a.ae=a.ae||[];a.ae.push(function(){a.Canvas.prototype.drawText=function(g,e,h,n,t){var w=ja(g),z=a._malloc(w+1);ka(g,C,z,w+1);this._drawSimpleText(z,w,e,h,t,n);a._free(z)};a.Canvas.prototype.drawGlyphs=function(g,e,h,n,t,w){if(!(2*g.length<=e.length))throw"Not enough positions for the array of gyphs";a.Yd(this.Xd);const z=l(g,"HEAPU16"),E=l(e,"HEAPF32");this._drawGlyphs(g.length,z,E,h,n,t,w);k(E,e);k(z,g)};a.Font.prototype.getGlyphBounds=
function(g,e,h){var n=l(g,"HEAPU16"),t=a._malloc(16*g.length);this._getGlyphWidthBounds(n,g.length,M,t,e||null);e=new Float32Array(a.HEAPU8.buffer,t,4*g.length);k(n,g);if(h)return h.set(e),a._free(t),h;g=Float32Array.from(e);a._free(t);return g};a.Font.prototype.getGlyphIDs=function(g,e,h){e||(e=g.length);var n=ja(g)+1,t=a._malloc(n);ka(g,C,t,n);g=a._malloc(2*e);e=this._getGlyphIDs(t,n-1,e,g);a._free(t);if(0>e)return a._free(g),null;t=new Uint16Array(a.HEAPU8.buffer,g,e);if(h)return h.set(t),a._free(g),
h;h=Uint16Array.from(t);a._free(g);return h};a.Font.prototype.getGlyphIntercepts=function(g,e,h,n){var t=l(g,"HEAPU16"),w=l(e,"HEAPF32");return this._getGlyphIntercepts(t,g.length,!(g&&g._ck),w,e.length,!(e&&e._ck),h,n)};a.Font.prototype.getGlyphWidths=function(g,e,h){var n=l(g,"HEAPU16"),t=a._malloc(4*g.length);this._getGlyphWidthBounds(n,g.length,t,M,e||null);e=new Float32Array(a.HEAPU8.buffer,t,g.length);k(n,g);if(h)return h.set(e),a._free(t),h;g=Float32Array.from(e);a._free(t);return g};a.FontMgr.FromData=
function(){if(!arguments.length)return null;var g=arguments;1===g.length&&Array.isArray(g[0])&&(g=arguments[0]);if(!g.length)return null;for(var e=[],h=[],n=0;n<g.length;n++){var t=new Uint8Array(g[n]),w=l(t,"HEAPU8");e.push(w);h.push(t.byteLength)}e=l(e,"HEAPU32");h=l(h,"HEAPU32");g=a.FontMgr._fromData(e,h,g.length);a._free(e);a._free(h);return g};a.Typeface.MakeTypefaceFromData=function(g){g=new Uint8Array(g);var e=l(g,"HEAPU8");return(g=a.Typeface._MakeTypefaceFromData(e,g.byteLength))?g:null};
a.Typeface.MakeFreeTypeFaceFromData=a.Typeface.MakeTypefaceFromData;a.Typeface.prototype.getGlyphIDs=function(g,e,h){e||(e=g.length);var n=ja(g)+1,t=a._malloc(n);ka(g,C,t,n);g=a._malloc(2*e);e=this._getGlyphIDs(t,n-1,e,g);a._free(t);if(0>e)return a._free(g),null;t=new Uint16Array(a.HEAPU8.buffer,g,e);if(h)return h.set(t),a._free(g),h;h=Uint16Array.from(t);a._free(g);return h};a.TextBlob.MakeOnPath=function(g,e,h,n){if(g&&g.length&&e&&e.countPoints()){if(1===e.countPoints())return this.MakeFromText(g,
h);n||(n=0);var t=h.getGlyphIDs(g);t=h.getGlyphWidths(t);var w=[];e=new a.ContourMeasureIter(e,!1,1);for(var z=e.next(),E=new Float32Array(4),K=0;K<g.length&&z;K++){var I=t[K];n+=I/2;if(n>z.length()){z.delete();z=e.next();if(!z){g=g.substring(0,K);break}n=I/2}z.getPosTan(n,E);var U=E[2],V=E[3];w.push(U,V,E[0]-I/2*U,E[1]-I/2*V);n+=I/2}g=this.MakeFromRSXform(g,w,h);z&&z.delete();e.delete();return g}};a.TextBlob.MakeFromRSXform=function(g,e,h){var n=ja(g)+1,t=a._malloc(n);ka(g,C,t,n);g=l(e,"HEAPF32");
h=a.TextBlob._MakeFromRSXform(t,n-1,g,h);a._free(t);return h?h:null};a.TextBlob.MakeFromRSXformGlyphs=function(g,e,h){var n=l(g,"HEAPU16");e=l(e,"HEAPF32");h=a.TextBlob._MakeFromRSXformGlyphs(n,2*g.length,e,h);k(n,g);return h?h:null};a.TextBlob.MakeFromGlyphs=function(g,e){var h=l(g,"HEAPU16");e=a.TextBlob._MakeFromGlyphs(h,2*g.length,e);k(h,g);return e?e:null};a.TextBlob.MakeFromText=function(g,e){var h=ja(g)+1,n=a._malloc(h);ka(g,C,n,h);g=a.TextBlob._MakeFromText(n,h-1,e);a._free(n);return g?g:
null};a.MallocGlyphIDs=function(g){return a.Malloc(Uint16Array,g)}});a.ae=a.ae||[];a.ae.push(function(){a.MakePicture=function(g){g=new Uint8Array(g);var e=a._malloc(g.byteLength);a.HEAPU8.set(g,e);return(g=a._MakePicture(e,g.byteLength))?g:null}});a.ae=a.ae||[];a.ae.push(function(){a.RuntimeEffect.Make=function(g,e){return a.RuntimeEffect._Make(g,{onError:e||function(h){console.log("RuntimeEffect error",h)}})};a.RuntimeEffect.MakeForBlender=function(g,e){return a.RuntimeEffect._MakeForBlender(g,
{onError:e||function(h){console.log("RuntimeEffect error",h)}})};a.RuntimeEffect.prototype.makeShader=function(g,e){var h=!g._ck,n=l(g,"HEAPF32");e=p(e);return this._makeShader(n,4*g.length,h,e)};a.RuntimeEffect.prototype.makeShaderWithChildren=function(g,e,h){var n=!g._ck,t=l(g,"HEAPF32");h=p(h);for(var w=[],z=0;z<e.length;z++)w.push(e[z].zd.Zd);e=l(w,"HEAPU32");return this._makeShaderWithChildren(t,4*g.length,n,e,w.length,h)};a.RuntimeEffect.prototype.makeBlender=function(g){var e=!g._ck,h=l(g,
"HEAPF32");return this._makeBlender(h,4*g.length,e)}})})(r);var la=Object.assign({},r),ma="./this.program",na=(a,b)=>{throw b;},pa="object"==typeof window,qa="function"==typeof importScripts,sa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,ta="",ua,va,xa;
if(sa){const {createRequire:a}=await import("module");var require=a(import.meta.url),fs=require("fs"),ya=require("path");qa?ta=ya.dirname(ta)+"/":ta=require("url").fileURLToPath(new URL("./",import.meta.url));ua=(b,c)=>{b=b.startsWith("file://")?new URL(b):ya.normalize(b);return fs.readFileSync(b,c?void 0:"utf8")};xa=b=>{b=ua(b,!0);b.buffer||(b=new Uint8Array(b));return b};va=(b,c,d,f=!0)=>{b=b.startsWith("file://")?new URL(b):ya.normalize(b);fs.readFile(b,f?void 0:
"utf8",(k,l)=>{k?d(k):c(f?l.buffer:l)})};!r.thisProgram&&1<process.argv.length&&(ma=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);na=(b,c)=>{process.exitCode=b;throw c;};r.inspect=()=>"[Emscripten Module object]"}else if(pa||qa)qa?ta=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ta=document.currentScript.src),_scriptDir&&(ta=_scriptDir),0!==ta.indexOf("blob:")?ta=ta.substr(0,ta.replace(/[?#].*/,"").lastIndexOf("/")+1):ta="",ua=a=>{var b=new XMLHttpRequest;b.open("GET",
a,!1);b.send(null);return b.responseText},qa&&(xa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),va=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var za=r.print||console.log.bind(console),Ba=r.printErr||console.error.bind(console);Object.assign(r,la);la=null;r.thisProgram&&(ma=r.thisProgram);
r.quit&&(na=r.quit);var Da;r.wasmBinary&&(Da=r.wasmBinary);var noExitRuntime=r.noExitRuntime||!0;"object"!=typeof WebAssembly&&Ea("no native wasm support detected");var Fa,G,Ga=!1,Ha,C,Ia,Ja,J,L,N,Ka;function La(){var a=Fa.buffer;r.HEAP8=Ha=new Int8Array(a);r.HEAP16=Ia=new Int16Array(a);r.HEAP32=J=new Int32Array(a);r.HEAPU8=C=new Uint8Array(a);r.HEAPU16=Ja=new Uint16Array(a);r.HEAPU32=L=new Uint32Array(a);r.HEAPF32=N=new Float32Array(a);r.HEAPF64=Ka=new Float64Array(a)}var Ma,Na=[],Oa=[],Qa=[];
function Ra(){var a=r.preRun.shift();Na.unshift(a)}var Sa=0,Va=null,Wa=null;function Ea(a){if(r.onAbort)r.onAbort(a);a="Aborted("+a+")";Ba(a);Ga=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}function Xa(a){return a.startsWith("data:application/octet-stream;base64,")}var Ya;if(r.locateFile){if(Ya="canvaskit.wasm",!Xa(Ya)){var Za=Ya;Ya=r.locateFile?r.locateFile(Za,ta):ta+Za}}else Ya=(new URL("canvaskit.wasm",import.meta.url)).href;
function $a(a){if(a==Ya&&Da)return new Uint8Array(Da);if(xa)return xa(a);throw"both async and sync fetching of the wasm failed";}function ab(a){if(!Da&&(pa||qa)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>$a(a));if(va)return new Promise((b,c)=>{va(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>$a(a))}
function bb(a,b,c){return ab(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{Ba("failed to asynchronously prepare wasm: "+d);Ea(d)})}
function cb(a,b){var c=Ya;return Da||"function"!=typeof WebAssembly.instantiateStreaming||Xa(c)||c.startsWith("file://")||sa||"function"!=typeof fetch?bb(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(f){Ba("wasm streaming compile failed: "+f);Ba("falling back to ArrayBuffer instantiation");return bb(c,a,b)}))}function db(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var eb=a=>{for(;0<a.length;)a.shift()(r)};
function fb(a){this.Zd=a-24;this.df=function(b){L[this.Zd+4>>2]=b};this.Me=function(b){L[this.Zd+8>>2]=b};this.re=function(b,c){this.Le();this.df(b);this.Me(c)};this.Le=function(){L[this.Zd+16>>2]=0}}
var gb=0,hb=0,jb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,kb=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&jb)return jb.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var k=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|k);else{var l=a[b++]&63;f=224==(f&240)?(f&15)<<12|k<<6|l:(f&7)<<18|k<<12|l<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d},
lb={};function mb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function nb(a){return this.fromWireType(J[a>>2])}var ob={},pb={},qb={},rb=void 0;function sb(a){throw new rb(a);}
function tb(a,b,c){function d(m){m=c(m);m.length!==a.length&&sb("Mismatched type converter count");for(var p=0;p<a.length;++p)ub(a[p],m[p])}a.forEach(function(m){qb[m]=b});var f=Array(b.length),k=[],l=0;b.forEach((m,p)=>{pb.hasOwnProperty(m)?f[p]=pb[m]:(k.push(m),ob.hasOwnProperty(m)||(ob[m]=[]),ob[m].push(()=>{f[p]=pb[m];++l;l===k.length&&d(f)}))});0===k.length&&d(f)}
function vb(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError(`Unknown type size: ${a}`);}}var wb=void 0;function O(a){for(var b="";C[a];)b+=wb[C[a++]];return b}var xb=void 0;function P(a){throw new xb(a);}
function yb(a,b,c={}){var d=b.name;a||P(`type "${d}" must have a positive integer typeid pointer`);if(pb.hasOwnProperty(a)){if(c.wf)return;P(`Cannot register type '${d}' twice`)}pb[a]=b;delete qb[a];ob.hasOwnProperty(a)&&(b=ob[a],delete ob[a],b.forEach(f=>f()))}function ub(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");yb(a,b,c)}function zb(a){P(a.zd.be.$d.name+" instance already deleted")}var Ab=!1;function Bb(){}
function Cb(a){--a.count.value;0===a.count.value&&(a.de?a.he.me(a.de):a.be.$d.me(a.Zd))}function Db(a,b,c){if(b===c)return a;if(void 0===c.ee)return null;a=Db(a,b,c.ee);return null===a?null:c.nf(a)}var Eb={},Kb=[];function Lb(){for(;Kb.length;){var a=Kb.pop();a.zd.ue=!1;a["delete"]()}}var Mb=void 0,Nb={};function Ob(a,b){for(void 0===b&&P("ptr should not be undefined");a.ee;)b=a.Ae(b),a=a.ee;return Nb[b]}
function Pb(a,b){b.be&&b.Zd||sb("makeClassHandle requires ptr and ptrType");!!b.he!==!!b.de&&sb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Qb(Object.create(a,{zd:{value:b}}))}function Qb(a){if("undefined"===typeof FinalizationRegistry)return Qb=b=>b,a;Ab=new FinalizationRegistry(b=>{Cb(b.zd)});Qb=b=>{var c=b.zd;c.de&&Ab.register(b,{zd:c},b);return b};Bb=b=>{Ab.unregister(b)};return Qb(a)}function Rb(){}
function Sb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a}function Tb(a,b){a=Sb(a);return{[a]:function(){return b.apply(this,arguments)}}[a]}
function Ub(a,b,c){if(void 0===a[b].ce){var d=a[b];a[b]=function(){a[b].ce.hasOwnProperty(arguments.length)||P(`Function '${c}' called with an invalid number of arguments (${arguments.length}) - expects one of (${a[b].ce})!`);return a[b].ce[arguments.length].apply(this,arguments)};a[b].ce=[];a[b].ce[d.se]=d}}
function Vb(a,b,c){r.hasOwnProperty(a)?((void 0===c||void 0!==r[a].ce&&void 0!==r[a].ce[c])&&P(`Cannot register public name '${a}' twice`),Ub(r,a,a),r.hasOwnProperty(c)&&P(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`),r[a].ce[c]=b):(r[a]=b,void 0!==c&&(r[a].Mf=c))}function Wb(a,b,c,d,f,k,l,m){this.name=a;this.constructor=b;this.ve=c;this.me=d;this.ee=f;this.rf=k;this.Ae=l;this.nf=m;this.Af=[]}
function Xb(a,b,c){for(;b!==c;)b.Ae||P(`Expected null or instance of ${c.name}, got an instance of ${b.name}`),a=b.Ae(a),b=b.ee;return a}function Yb(a,b){if(null===b)return this.Qe&&P(`null is not a valid ${this.name}`),0;b.zd||P(`Cannot pass "${Zb(b)}" as a ${this.name}`);b.zd.Zd||P(`Cannot pass deleted object as a pointer of type ${this.name}`);return Xb(b.zd.Zd,b.zd.be.$d,this.$d)}
function $b(a,b){if(null===b){this.Qe&&P(`null is not a valid ${this.name}`);if(this.Fe){var c=this.Re();null!==a&&a.push(this.me,c);return c}return 0}b.zd||P(`Cannot pass "${Zb(b)}" as a ${this.name}`);b.zd.Zd||P(`Cannot pass deleted object as a pointer of type ${this.name}`);!this.Ee&&b.zd.be.Ee&&P(`Cannot convert argument of type ${b.zd.he?b.zd.he.name:b.zd.be.name} to parameter type ${this.name}`);c=Xb(b.zd.Zd,b.zd.be.$d,this.$d);if(this.Fe)switch(void 0===b.zd.de&&P("Passing raw pointer to smart pointer is illegal"),
this.Ff){case 0:b.zd.he===this?c=b.zd.de:P(`Cannot convert argument of type ${b.zd.he?b.zd.he.name:b.zd.be.name} to parameter type ${this.name}`);break;case 1:c=b.zd.de;break;case 2:if(b.zd.he===this)c=b.zd.de;else{var d=b.clone();c=this.Bf(c,ac(function(){d["delete"]()}));null!==a&&a.push(this.me,c)}break;default:P("Unsupporting sharing policy")}return c}
function bc(a,b){if(null===b)return this.Qe&&P(`null is not a valid ${this.name}`),0;b.zd||P(`Cannot pass "${Zb(b)}" as a ${this.name}`);b.zd.Zd||P(`Cannot pass deleted object as a pointer of type ${this.name}`);b.zd.be.Ee&&P(`Cannot convert argument of type ${b.zd.be.name} to parameter type ${this.name}`);return Xb(b.zd.Zd,b.zd.be.$d,this.$d)}
function cc(a,b,c,d,f,k,l,m,p,x,y){this.name=a;this.$d=b;this.Qe=c;this.Ee=d;this.Fe=f;this.zf=k;this.Ff=l;this.Ze=m;this.Re=p;this.Bf=x;this.me=y;f||void 0!==b.ee?this.toWireType=$b:(this.toWireType=d?Yb:bc,this.ge=null)}function dc(a,b,c){r.hasOwnProperty(a)||sb("Replacing nonexistant public symbol");void 0!==r[a].ce&&void 0!==c?r[a].ce[c]=b:(r[a]=b,r[a].se=c)}
var ec=(a,b)=>{var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=r["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=Ma.get(b).apply(null,c);return d}};function fc(a,b){a=O(a);var c=a.includes("j")?ec(a,b):Ma.get(b);"function"!=typeof c&&P(`unknown function pointer with signature ${a}: ${b}`);return c}var nc=void 0;function oc(a){a=pc(a);var b=O(a);qc(a);return b}
function rc(a,b){function c(k){f[k]||pb[k]||(qb[k]?qb[k].forEach(c):(d.push(k),f[k]=!0))}var d=[],f={};b.forEach(c);throw new nc(`${a}: `+d.map(oc).join([", "]));}
function sc(a,b,c,d,f){var k=b.length;2>k&&P("argTypes array size mismatch! Must at least get return value and 'this' types!");var l=null!==b[1]&&null!==c,m=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].ge){m=!0;break}var p="void"!==b[0].name,x=k-2,y=Array(x),B=[],D=[];return function(){arguments.length!==x&&P(`function ${a} called with ${arguments.length} arguments, expected ${x} args!`);D.length=0;B.length=l?2:1;B[0]=f;if(l){var u=b[1].toWireType(D,this);B[1]=u}for(var F=0;F<x;++F)y[F]=
b[F+2].toWireType(D,arguments[F]),B.push(y[F]);F=d.apply(null,B);if(m)mb(D);else for(var H=l?1:2;H<b.length;H++){var T=1===H?u:y[H-2];null!==b[H].ge&&b[H].ge(T)}u=p?b[0].fromWireType(F):void 0;return u}}function tc(a,b){for(var c=[],d=0;d<a;d++)c.push(L[b+4*d>>2]);return c}function uc(){this.le=[void 0];this.Xe=[]}var vc=new uc;function wc(a){a>=vc.re&&0===--vc.get(a).$e&&vc.Me(a)}
var xc=a=>{a||P("Cannot use deleted val. handle = "+a);return vc.get(a).value},ac=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:return vc.Le({$e:1,value:a})}};function yc(a,b,c){switch(b){case 0:return function(d){return this.fromWireType((c?Ha:C)[d])};case 1:return function(d){return this.fromWireType((c?Ia:Ja)[d>>1])};case 2:return function(d){return this.fromWireType((c?J:L)[d>>2])};default:throw new TypeError("Unknown integer type: "+a);}}
function zc(a,b){var c=pb[a];void 0===c&&P(b+" has unknown type "+oc(a));return c}function Zb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Ac(a,b){switch(b){case 2:return function(c){return this.fromWireType(N[c>>2])};case 3:return function(c){return this.fromWireType(Ka[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Bc(a,b,c){switch(b){case 0:return c?function(d){return Ha[d]}:function(d){return C[d]};case 1:return c?function(d){return Ia[d>>1]}:function(d){return Ja[d>>1]};case 2:return c?function(d){return J[d>>2]}:function(d){return L[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}
var ka=(a,b,c,d)=>{if(!(0<d))return 0;var f=c;d=c+d-1;for(var k=0;k<a.length;++k){var l=a.charCodeAt(k);if(55296<=l&&57343>=l){var m=a.charCodeAt(++k);l=65536+((l&1023)<<10)|m&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-f},ja=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=
d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Cc="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Dc=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&Ja[c];)++c;c<<=1;if(32<c-a&&Cc)return Cc.decode(C.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var f=Ia[a+2*d>>1];if(0==f)break;c+=String.fromCharCode(f)}return c},Ec=(a,b,c)=>{void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)Ia[b>>1]=a.charCodeAt(f),b+=2;Ia[b>>1]=0;return b-d},
Fc=a=>2*a.length,Gc=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var f=J[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d},Hc=(a,b,c)=>{void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var l=a.charCodeAt(++f);k=65536+((k&1023)<<10)|l&1023}J[b>>2]=k;b+=4;if(b+4>c)break}J[b>>2]=0;return b-d},Ic=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);
55296<=d&&57343>=d&&++c;b+=4}return b},Jc={};function Kc(a){var b=Jc[a];return void 0===b?O(a):b}var Lc=[];
function Mc(){function a(b){b.$$$embind_global$$$=b;var c="object"==typeof $$$embind_global$$$&&b.$$$embind_global$$$==b;c||delete b.$$$embind_global$$$;return c}if("object"==typeof globalThis)return globalThis;if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;"object"==typeof global&&a(global)?$$$embind_global$$$=global:"object"==typeof self&&a(self)&&($$$embind_global$$$=self);if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;throw Error("unable to get global object.");
}function Nc(a){var b=Lc.length;Lc.push(a);return b}function Oc(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=zc(L[b+4*d>>2],"parameter "+d);return c}var Pc=[];function Qc(a){var b=Array(a+1);return function(c,d,f){b[0]=c;for(var k=0;k<a;++k){var l=zc(L[d+4*k>>2],"parameter "+k);b[k+1]=l.readValueFromPointer(f);f+=l.argPackAdvance}c=new (c.bind.apply(c,b));return ac(c)}}var Rc={};
function Sc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,k){b.drawArraysInstancedANGLE(c,d,f,k)},a.drawElementsInstanced=function(c,d,f,k,l){b.drawElementsInstancedANGLE(c,d,f,k,l)})}
function Tc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Uc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
var Vc=1,Wc=[],Xc=[],Yc=[],Zc=[],ea=[],$c=[],ad=[],ia=[],bd=[],cd=[],dd=[],ed={},fd={},gd=4;function R(a){hd||(hd=a)}function da(a){for(var b=Vc++,c=a.length;c<b;c++)a[c]=null;return b}function fa(a,b){a.re||(a.re=a.getContext,a.getContext=function(d,f){f=a.re(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=1<b.majorVersion?a.getContext("webgl2",b):a.getContext("webgl",b);return c?kd(c,b):0}
function kd(a,b){var c=da(ia),d={handle:c,attributes:b,version:b.majorVersion,ie:a};a.canvas&&(a.canvas.cf=d);ia[c]=d;("undefined"==typeof b.pf||b.pf)&&ld(d);return c}function ha(a){v=ia[a];r.Kf=S=v&&v.ie;return!(a&&!S)}
function ld(a){a||(a=v);if(!a.xf){a.xf=!0;var b=a.ie;Sc(b);Tc(b);Uc(b);b.Ve=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Ye=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.je=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.je)b.je=b.getExtension("EXT_disjoint_timer_query");b.Lf=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var v,hd,md={},od=()=>{if(!nd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ma||"./this.program"},b;for(b in md)void 0===md[b]?delete a[b]:a[b]=md[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);nd=c}return nd},nd,pd=[null,[],[]];function qd(a){S.bindVertexArray(ad[a])}
function rd(a,b){for(var c=0;c<a;c++){var d=J[b+4*c>>2];S.deleteVertexArray(ad[d]);ad[d]=null}}var sd=[];function td(a,b,c,d){S.drawElements(a,b,c,d)}function ud(a,b,c,d){for(var f=0;f<a;f++){var k=S[c](),l=k&&da(d);k?(k.name=l,d[l]=k):R(1282);J[b+4*f>>2]=l}}function vd(a,b){ud(a,b,"createVertexArray",ad)}function wd(a,b){L[a>>2]=b;L[a+4>>2]=(b-L[a>>2])/4294967296}
function xd(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&R(1280);return;case 34814:case 36345:d=0;break;case 34466:var f=S.getParameter(34467);d=f?f.length:0;break;case 33309:if(2>v.version){R(1282);return}d=2*(S.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>v.version){R(1280);return}d=33307==a?3:0}if(void 0===d)switch(f=S.getParameter(a),typeof f){case "number":d=f;break;case "boolean":d=f?1:0;break;case "string":R(1280);return;case "object":if(null===
f)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:R(1280);return}else{if(f instanceof Float32Array||f instanceof Uint32Array||f instanceof Int32Array||f instanceof Array){for(a=0;a<f.length;++a)switch(c){case 0:J[b+4*a>>2]=f[a];break;case 2:N[b+4*a>>2]=f[a];break;case 4:Ha[b+a>>0]=f[a]?1:0}return}try{d=f.name|0}catch(k){R(1280);
Ba("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+k+")");return}}break;default:R(1280);Ba("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+f+" of type "+typeof f+"!");return}switch(c){case 1:wd(b,d);break;case 0:J[b>>2]=d;break;case 2:N[b>>2]=d;break;case 4:Ha[b>>0]=d?1:0}}else R(1281)}
function yd(a,b,c){if(c){a=bd[a];b=2>v.version?S.je.getQueryObjectEXT(a,b):S.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;wd(c,d)}else R(1281)}var Ad=a=>{var b=ja(a)+1,c=zd(b);c&&ka(a,C,c,b);return c};function Bd(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Cd(a){a-=5120;return 0==a?Ha:1==a?C:2==a?Ia:4==a?J:6==a?N:5==a||28922==a||28520==a||30779==a||30782==a?L:Ja}
function Dd(a,b,c,d,f){a=Cd(a);var k=31-Math.clz32(a.BYTES_PER_ELEMENT),l=gd;return a.subarray(f>>k,f+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<k)+l-1&-l)>>k)}function W(a){var b=S.lf;if(b){var c=b.ze[a];"number"==typeof c&&(b.ze[a]=c=S.getUniformLocation(b,b.af[a]+(0<c?"["+c+"]":"")));return c}R(1282)}var Ed=[],Fd=[],Gd=a=>0===a%4&&(0!==a%100||0===a%400),Hd=[31,29,31,30,31,30,31,31,30,31,30,31],Id=[31,28,31,30,31,30,31,31,30,31,30,31];
function Jd(a){var b=Array(ja(a)+1);ka(a,b,0,b.length);return b}
var Kd=(a,b,c,d)=>{function f(u,F,H){for(u="number"==typeof u?u.toString():u||"";u.length<F;)u=H[0]+u;return u}function k(u,F){return f(u,F,"0")}function l(u,F){function H(ca){return 0>ca?-1:0<ca?1:0}var T;0===(T=H(u.getFullYear()-F.getFullYear()))&&0===(T=H(u.getMonth()-F.getMonth()))&&(T=H(u.getDate()-F.getDate()));return T}function m(u){switch(u.getDay()){case 0:return new Date(u.getFullYear()-1,11,29);case 1:return u;case 2:return new Date(u.getFullYear(),0,3);case 3:return new Date(u.getFullYear(),
0,2);case 4:return new Date(u.getFullYear(),0,1);case 5:return new Date(u.getFullYear()-1,11,31);case 6:return new Date(u.getFullYear()-1,11,30)}}function p(u){var F=u.oe;for(u=new Date((new Date(u.pe+1900,0,1)).getTime());0<F;){var H=u.getMonth(),T=(Gd(u.getFullYear())?Hd:Id)[H];if(F>T-u.getDate())F-=T-u.getDate()+1,u.setDate(1),11>H?u.setMonth(H+1):(u.setMonth(0),u.setFullYear(u.getFullYear()+1));else{u.setDate(u.getDate()+F);break}}H=new Date(u.getFullYear()+1,0,4);F=m(new Date(u.getFullYear(),
0,4));H=m(H);return 0>=l(F,u)?0>=l(H,u)?u.getFullYear()+1:u.getFullYear():u.getFullYear()-1}var x=J[d+40>>2];d={If:J[d>>2],Hf:J[d+4>>2],Je:J[d+8>>2],Se:J[d+12>>2],Ke:J[d+16>>2],pe:J[d+20>>2],ke:J[d+24>>2],oe:J[d+28>>2],Of:J[d+32>>2],Gf:J[d+36>>2],Jf:x?x?kb(C,x):"":""};c=c?kb(C,c):"";x={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y",
"%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var y in x)c=c.replace(new RegExp(y,"g"),x[y]);var B="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),D="January February March April May June July August September October November December".split(" ");x={"%a":u=>B[u.ke].substring(0,3),"%A":u=>B[u.ke],"%b":u=>D[u.Ke].substring(0,3),"%B":u=>D[u.Ke],"%C":u=>k((u.pe+1900)/
100|0,2),"%d":u=>k(u.Se,2),"%e":u=>f(u.Se,2," "),"%g":u=>p(u).toString().substring(2),"%G":u=>p(u),"%H":u=>k(u.Je,2),"%I":u=>{u=u.Je;0==u?u=12:12<u&&(u-=12);return k(u,2)},"%j":u=>{for(var F=0,H=0;H<=u.Ke-1;F+=(Gd(u.pe+1900)?Hd:Id)[H++]);return k(u.Se+F,3)},"%m":u=>k(u.Ke+1,2),"%M":u=>k(u.Hf,2),"%n":()=>"\n","%p":u=>0<=u.Je&&12>u.Je?"AM":"PM","%S":u=>k(u.If,2),"%t":()=>"\t","%u":u=>u.ke||7,"%U":u=>k(Math.floor((u.oe+7-u.ke)/7),2),"%V":u=>{var F=Math.floor((u.oe+7-(u.ke+6)%7)/7);2>=(u.ke+371-u.oe-
2)%7&&F++;if(F)53==F&&(H=(u.ke+371-u.oe)%7,4==H||3==H&&Gd(u.pe)||(F=1));else{F=52;var H=(u.ke+7-u.oe-1)%7;(4==H||5==H&&Gd(u.pe%400-1))&&F++}return k(F,2)},"%w":u=>u.ke,"%W":u=>k(Math.floor((u.oe+7-(u.ke+6)%7)/7),2),"%y":u=>(u.pe+1900).toString().substring(2),"%Y":u=>u.pe+1900,"%z":u=>{u=u.Gf;var F=0<=u;u=Math.abs(u)/60;return(F?"+":"-")+String("0000"+(u/60*100+u%60)).slice(-4)},"%Z":u=>u.Jf,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(y in x)c.includes(y)&&(c=c.replace(new RegExp(y,"g"),x[y](d)));
c=c.replace(/\0\0/g,"%");y=Jd(c);if(y.length>b)return 0;Ha.set(y,a);return y.length-1};rb=r.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};for(var Ld=Array(256),Md=0;256>Md;++Md)Ld[Md]=String.fromCharCode(Md);wb=Ld;xb=r.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
Rb.prototype.isAliasOf=function(a){if(!(this instanceof Rb&&a instanceof Rb))return!1;var b=this.zd.be.$d,c=this.zd.Zd,d=a.zd.be.$d;for(a=a.zd.Zd;b.ee;)c=b.Ae(c),b=b.ee;for(;d.ee;)a=d.Ae(a),d=d.ee;return b===d&&c===a};
Rb.prototype.clone=function(){this.zd.Zd||zb(this);if(this.zd.ye)return this.zd.count.value+=1,this;var a=Qb,b=Object,c=b.create,d=Object.getPrototypeOf(this),f=this.zd;a=a(c.call(b,d,{zd:{value:{count:f.count,ue:f.ue,ye:f.ye,Zd:f.Zd,be:f.be,de:f.de,he:f.he}}}));a.zd.count.value+=1;a.zd.ue=!1;return a};Rb.prototype["delete"]=function(){this.zd.Zd||zb(this);this.zd.ue&&!this.zd.ye&&P("Object already scheduled for deletion");Bb(this);Cb(this.zd);this.zd.ye||(this.zd.de=void 0,this.zd.Zd=void 0)};
Rb.prototype.isDeleted=function(){return!this.zd.Zd};Rb.prototype.deleteLater=function(){this.zd.Zd||zb(this);this.zd.ue&&!this.zd.ye&&P("Object already scheduled for deletion");Kb.push(this);1===Kb.length&&Mb&&Mb(Lb);this.zd.ue=!0;return this};r.getInheritedInstanceCount=function(){return Object.keys(Nb).length};r.getLiveInheritedInstances=function(){var a=[],b;for(b in Nb)Nb.hasOwnProperty(b)&&a.push(Nb[b]);return a};r.flushPendingDeletes=Lb;r.setDelayFunction=function(a){Mb=a;Kb.length&&Mb&&Mb(Lb)};
cc.prototype.sf=function(a){this.Ze&&(a=this.Ze(a));return a};cc.prototype.Ue=function(a){this.me&&this.me(a)};cc.prototype.argPackAdvance=8;cc.prototype.readValueFromPointer=nb;cc.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
cc.prototype.fromWireType=function(a){function b(){return this.Fe?Pb(this.$d.ve,{be:this.zf,Zd:c,he:this,de:a}):Pb(this.$d.ve,{be:this,Zd:a})}var c=this.sf(a);if(!c)return this.Ue(a),null;var d=Ob(this.$d,c);if(void 0!==d){if(0===d.zd.count.value)return d.zd.Zd=c,d.zd.de=a,d.clone();d=d.clone();this.Ue(a);return d}d=this.$d.rf(c);d=Eb[d];if(!d)return b.call(this);d=this.Ee?d.kf:d.pointerType;var f=Db(c,this.$d,d.$d);return null===f?b.call(this):this.Fe?Pb(d.$d.ve,{be:d,Zd:f,he:this,de:a}):Pb(d.$d.ve,
{be:d,Zd:f})};nc=r.UnboundTypeError=function(a,b){var c=Tb(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c}(Error,"UnboundTypeError");
Object.assign(uc.prototype,{get(a){return this.le[a]},has(a){return void 0!==this.le[a]},Le(a){var b=this.Xe.pop()||this.le.length;this.le[b]=a;return b},Me(a){this.le[a]=void 0;this.Xe.push(a)}});vc.le.push({value:void 0},{value:null},{value:!0},{value:!1});vc.re=vc.le.length;r.count_emval_handles=function(){for(var a=0,b=vc.re;b<vc.le.length;++b)void 0!==vc.le[b]&&++a;return a};for(var S,Nd=0;32>Nd;++Nd)sd.push(Array(Nd));var Od=new Float32Array(288);
for(Nd=0;288>Nd;++Nd)Ed[Nd]=Od.subarray(0,Nd+1);var Pd=new Int32Array(288);for(Nd=0;288>Nd;++Nd)Fd[Nd]=Pd.subarray(0,Nd+1);
var ce={H:function(a,b,c){(new fb(a)).re(b,c);gb=a;hb++;throw gb;},$:function(){return 0},od:()=>{},nd:function(){return 0},md:()=>{},ld:()=>{},_:function(){},kd:()=>{},D:function(a){var b=lb[a];delete lb[a];var c=b.Re,d=b.me,f=b.We,k=f.map(l=>l.vf).concat(f.map(l=>l.Df));tb([a],k,l=>{var m={};f.forEach((p,x)=>{var y=l[x],B=p.tf,D=p.uf,u=l[x+f.length],F=p.Cf,H=p.Ef;m[p.qf]={read:T=>y.fromWireType(B(D,T)),write:(T,ca)=>{var Y=[];F(H,T,u.toWireType(Y,ca));mb(Y)}}});return[{name:b.name,fromWireType:function(p){var x=
{},y;for(y in m)x[y]=m[y].read(p);d(p);return x},toWireType:function(p,x){for(var y in m)if(!(y in x))throw new TypeError(`Missing field: "${y}"`);var B=c();for(y in m)m[y].write(B,x[y]);null!==p&&p.push(d,B);return B},argPackAdvance:8,readValueFromPointer:nb,ge:d}]})},fa:function(){},gd:function(a,b,c,d,f){var k=vb(c);b=O(b);ub(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,m){return m?d:f},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var m=Ha;else if(2===c)m=Ia;
else if(4===c)m=J;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(m[l>>k])},ge:null})},l:function(a,b,c,d,f,k,l,m,p,x,y,B,D){y=O(y);k=fc(f,k);m&&(m=fc(l,m));x&&(x=fc(p,x));D=fc(B,D);var u=Sb(y);Vb(u,function(){rc(`Cannot construct ${y} due to unbound types`,[d])});tb([a,b,c],d?[d]:[],function(F){F=F[0];if(d){var H=F.$d;var T=H.ve}else T=Rb.prototype;F=Tb(u,function(){if(Object.getPrototypeOf(this)!==ca)throw new xb("Use 'new' to construct "+y);if(void 0===Y.ne)throw new xb(y+
" has no accessible constructor");var Pa=Y.ne[arguments.length];if(void 0===Pa)throw new xb(`Tried to invoke ctor of ${y} with invalid number of parameters (${arguments.length}) - expected (${Object.keys(Y.ne).toString()}) parameters instead!`);return Pa.apply(this,arguments)});var ca=Object.create(T,{constructor:{value:F}});F.prototype=ca;var Y=new Wb(y,F,ca,D,H,k,m,x);Y.ee&&(void 0===Y.ee.Be&&(Y.ee.Be=[]),Y.ee.Be.push(Y));H=new cc(y,Y,!0,!1,!1);T=new cc(y+"*",Y,!1,!1,!1);var wa=new cc(y+" const*",
Y,!1,!0,!1);Eb[a]={pointerType:T,kf:wa};dc(u,F);return[H,T,wa]})},e:function(a,b,c,d,f,k,l){var m=tc(c,d);b=O(b);k=fc(f,k);tb([],[a],function(p){function x(){rc(`Cannot call ${y} due to unbound types`,m)}p=p[0];var y=`${p.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var B=p.$d.constructor;void 0===B[b]?(x.se=c-1,B[b]=x):(Ub(B,b,y),B[b].ce[c-1]=x);tb([],m,function(D){D=[D[0],null].concat(D.slice(1));D=sc(y,D,null,k,l);void 0===B[b].ce?(D.se=c-1,B[b]=D):B[b].ce[c-1]=D;if(p.$d.Be)for(const u of p.$d.Be)u.constructor.hasOwnProperty(b)||
(u.constructor[b]=D);return[]});return[]})},B:function(a,b,c,d,f,k){var l=tc(b,c);f=fc(d,f);tb([],[a],function(m){m=m[0];var p=`constructor ${m.name}`;void 0===m.$d.ne&&(m.$d.ne=[]);if(void 0!==m.$d.ne[b-1])throw new xb(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${m.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);m.$d.ne[b-1]=()=>{rc(`Cannot construct ${m.name} due to unbound types`,l)};
tb([],l,function(x){x.splice(1,0,null);m.$d.ne[b-1]=sc(p,x,null,f,k);return[]});return[]})},a:function(a,b,c,d,f,k,l,m){var p=tc(c,d);b=O(b);k=fc(f,k);tb([],[a],function(x){function y(){rc(`Cannot call ${B} due to unbound types`,p)}x=x[0];var B=`${x.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);m&&x.$d.Af.push(b);var D=x.$d.ve,u=D[b];void 0===u||void 0===u.ce&&u.className!==x.name&&u.se===c-2?(y.se=c-2,y.className=x.name,D[b]=y):(Ub(D,b,B),D[b].ce[c-2]=y);tb([],p,function(F){F=sc(B,F,
x,k,l);void 0===D[b].ce?(F.se=c-2,D[b]=F):D[b].ce[c-2]=F;return[]});return[]})},s:function(a,b,c){a=O(a);tb([],[b],function(d){d=d[0];r[a]=d.fromWireType(c);return[]})},fd:function(a,b){b=O(b);ub(a,{name:b,fromWireType:function(c){var d=xc(c);wc(c);return d},toWireType:function(c,d){return ac(d)},argPackAdvance:8,readValueFromPointer:nb,ge:null})},j:function(a,b,c,d){function f(){}c=vb(c);b=O(b);f.values={};ub(a,{name:b,constructor:f,fromWireType:function(k){return this.constructor.values[k]},toWireType:function(k,
l){return l.value},argPackAdvance:8,readValueFromPointer:yc(b,c,d),ge:null});Vb(b,f)},b:function(a,b,c){var d=zc(a,"enum");b=O(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Tb(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d},Y:function(a,b,c){c=vb(c);b=O(b);ub(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,f){return f},argPackAdvance:8,readValueFromPointer:Ac(b,c),ge:null})},v:function(a,b,c,d,f,k){var l=tc(b,c);a=O(a);f=
fc(d,f);Vb(a,function(){rc(`Cannot call ${a} due to unbound types`,l)},b-1);tb([],l,function(m){m=[m[0],null].concat(m.slice(1));dc(a,sc(a,m,null,f,k),b-1);return[]})},E:function(a,b,c,d,f){b=O(b);-1===f&&(f=4294967295);f=vb(c);var k=m=>m;if(0===d){var l=32-8*c;k=m=>m<<l>>>l}c=b.includes("unsigned")?function(m,p){return p>>>0}:function(m,p){return p};ub(a,{name:b,fromWireType:k,toWireType:c,argPackAdvance:8,readValueFromPointer:Bc(b,f,0!==d),ge:null})},r:function(a,b,c){function d(k){k>>=2;var l=
L;return new f(l.buffer,l[k+1],l[k])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=O(c);ub(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{wf:!0})},o:function(a,b,c,d,f,k,l,m,p,x,y,B){c=O(c);k=fc(f,k);m=fc(l,m);x=fc(p,x);B=fc(y,B);tb([a],[b],function(D){D=D[0];return[new cc(c,D.$d,!1,!1,!0,D,d,k,m,x,B)]})},X:function(a,b){b=O(b);var c="std::string"===b;ub(a,{name:b,fromWireType:function(d){var f=L[d>>2],k=d+4;if(c)for(var l=
k,m=0;m<=f;++m){var p=k+m;if(m==f||0==C[p]){l=l?kb(C,l,p-l):"";if(void 0===x)var x=l;else x+=String.fromCharCode(0),x+=l;l=p+1}}else{x=Array(f);for(m=0;m<f;++m)x[m]=String.fromCharCode(C[k+m]);x=x.join("")}qc(d);return x},toWireType:function(d,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var k="string"==typeof f;k||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||P("Cannot pass non-string to std::string");var l=c&&k?ja(f):f.length;var m=zd(4+l+1),p=m+4;L[m>>2]=
l;if(c&&k)ka(f,C,p,l+1);else if(k)for(k=0;k<l;++k){var x=f.charCodeAt(k);255<x&&(qc(p),P("String has UTF-16 code units that do not fit in 8 bits"));C[p+k]=x}else for(k=0;k<l;++k)C[p+k]=f[k];null!==d&&d.push(qc,m);return m},argPackAdvance:8,readValueFromPointer:nb,ge:function(d){qc(d)}})},O:function(a,b,c){c=O(c);if(2===b){var d=Dc;var f=Ec;var k=Fc;var l=()=>Ja;var m=1}else 4===b&&(d=Gc,f=Hc,k=Ic,l=()=>L,m=2);ub(a,{name:c,fromWireType:function(p){for(var x=L[p>>2],y=l(),B,D=p+4,u=0;u<=x;++u){var F=
p+4+u*b;if(u==x||0==y[F>>m])D=d(D,F-D),void 0===B?B=D:(B+=String.fromCharCode(0),B+=D),D=F+b}qc(p);return B},toWireType:function(p,x){"string"!=typeof x&&P(`Cannot pass non-string to C++ string type ${c}`);var y=k(x),B=zd(4+y+b);L[B>>2]=y>>m;f(x,B+4,y+b);null!==p&&p.push(qc,B);return B},argPackAdvance:8,readValueFromPointer:nb,ge:function(p){qc(p)}})},C:function(a,b,c,d,f,k){lb[a]={name:O(b),Re:fc(c,d),me:fc(f,k),We:[]}},d:function(a,b,c,d,f,k,l,m,p,x){lb[a].We.push({qf:O(b),vf:c,tf:fc(d,f),uf:k,
Df:l,Cf:fc(m,p),Ef:x})},ed:function(a,b){b=O(b);ub(a,{yf:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},dd:()=>!0,cd:()=>{throw Infinity;},G:function(a,b,c){a=xc(a);b=zc(b,"emval::as");var d=[],f=ac(d);L[c>>2]=f;return b.toWireType(d,a)},N:function(a,b,c,d,f){a=Lc[a];b=xc(b);c=Kc(c);var k=[];L[d>>2]=ac(k);return a(b,c,k,f)},t:function(a,b,c,d){a=Lc[a];b=xc(b);c=Kc(c);a(b,c,null,d)},c:wc,M:function(a){if(0===a)return ac(Mc());a=Kc(a);return ac(Mc()[a])},p:function(a,
b){var c=Oc(a,b),d=c[0];b=d.name+"_$"+c.slice(1).map(function(l){return l.name}).join("_")+"$";var f=Pc[b];if(void 0!==f)return f;var k=Array(a-1);f=Nc((l,m,p,x)=>{for(var y=0,B=0;B<a-1;++B)k[B]=c[B+1].readValueFromPointer(x+y),y+=c[B+1].argPackAdvance;l=l[m].apply(l,k);for(B=0;B<a-1;++B)c[B+1].mf&&c[B+1].mf(k[B]);if(!d.yf)return d.toWireType(p,l)});return Pc[b]=f},A:function(a,b){a=xc(a);b=xc(b);return ac(a[b])},m:function(a){4<a&&(vc.get(a).$e+=1)},L:function(a,b,c,d){a=xc(a);var f=Rc[b];f||(f=
Qc(b),Rc[b]=f);return f(a,c,d)},I:function(){return ac([])},f:function(a){return ac(Kc(a))},F:function(){return ac({})},bd:function(a){a=xc(a);return!a},z:function(a){var b=xc(a);mb(b);wc(a)},i:function(a,b,c){a=xc(a);b=xc(b);c=xc(c);a[b]=c},g:function(a,b){a=zc(a,"_emval_take_value");a=a.readValueFromPointer(b);return ac(a)},ea:function(){return-52},da:function(){},h:()=>{Ea("")},ad:()=>performance.now(),$c:a=>{var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);
d=Math.min(d,a+100663296);var f=Math;d=Math.max(a,d);a:{f=f.min.call(f,2147483648,d+(65536-d%65536)%65536)-Fa.buffer.byteLength+65535>>>16;try{Fa.grow(f);La();var k=1;break a}catch(l){}k=void 0}if(k)return!0}return!1},_c:function(){return v?v.handle:0},jd:(a,b)=>{var c=0;od().forEach(function(d,f){var k=b+c;f=L[a+4*f>>2]=k;for(k=0;k<d.length;++k)Ha[f++>>0]=d.charCodeAt(k);Ha[f>>0]=0;c+=d.length+1});return 0},id:(a,b)=>{var c=od();L[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});L[b>>
2]=d;return 0},Zc:a=>{if(!noExitRuntime){if(r.onExit)r.onExit(a);Ga=!0}na(a,new db(a))},P:()=>52,ha:function(){return 52},hd:()=>52,ga:function(){return 70},Z:(a,b,c,d)=>{for(var f=0,k=0;k<c;k++){var l=L[b>>2],m=L[b+4>>2];b+=8;for(var p=0;p<m;p++){var x=C[l+p],y=pd[a];0===x||10===x?((1===a?za:Ba)(kb(y,0)),y.length=0):y.push(x)}f+=m}L[d>>2]=f;return 0},Yc:function(a){S.activeTexture(a)},Xc:function(a,b){S.attachShader(Xc[a],$c[b])},Wc:function(a,b){S.beginQuery(a,bd[b])},Vc:function(a,b){S.je.beginQueryEXT(a,
bd[b])},Uc:function(a,b,c){S.bindAttribLocation(Xc[a],b,c?kb(C,c):"")},Tc:function(a,b){35051==a?S.Oe=b:35052==a&&(S.te=b);S.bindBuffer(a,Wc[b])},W:function(a,b){S.bindFramebuffer(a,Yc[b])},Sc:function(a,b){S.bindRenderbuffer(a,Zc[b])},Rc:function(a,b){S.bindSampler(a,cd[b])},Qc:function(a,b){S.bindTexture(a,ea[b])},Pc:qd,Oc:qd,Nc:function(a,b,c,d){S.blendColor(a,b,c,d)},Mc:function(a){S.blendEquation(a)},Lc:function(a,b){S.blendFunc(a,b)},Kc:function(a,b,c,d,f,k,l,m,p,x){S.blitFramebuffer(a,b,c,
d,f,k,l,m,p,x)},Jc:function(a,b,c,d){2<=v.version?c&&b?S.bufferData(a,C,d,c,b):S.bufferData(a,b,d):S.bufferData(a,c?C.subarray(c,c+b):b,d)},Ic:function(a,b,c,d){2<=v.version?c&&S.bufferSubData(a,b,C,d,c):S.bufferSubData(a,b,C.subarray(d,d+c))},Hc:function(a){return S.checkFramebufferStatus(a)},V:function(a){S.clear(a)},U:function(a,b,c,d){S.clearColor(a,b,c,d)},T:function(a){S.clearStencil(a)},ca:function(a,b,c,d){return S.clientWaitSync(dd[a],b,(c>>>0)+4294967296*d)},Gc:function(a,b,c,d){S.colorMask(!!a,
!!b,!!c,!!d)},Fc:function(a){S.compileShader($c[a])},Ec:function(a,b,c,d,f,k,l,m){2<=v.version?S.te||!l?S.compressedTexImage2D(a,b,c,d,f,k,l,m):S.compressedTexImage2D(a,b,c,d,f,k,C,m,l):S.compressedTexImage2D(a,b,c,d,f,k,m?C.subarray(m,m+l):null)},Dc:function(a,b,c,d,f,k,l,m,p){2<=v.version?S.te||!m?S.compressedTexSubImage2D(a,b,c,d,f,k,l,m,p):S.compressedTexSubImage2D(a,b,c,d,f,k,l,C,p,m):S.compressedTexSubImage2D(a,b,c,d,f,k,l,p?C.subarray(p,p+m):null)},Cc:function(a,b,c,d,f){S.copyBufferSubData(a,
b,c,d,f)},Bc:function(a,b,c,d,f,k,l,m){S.copyTexSubImage2D(a,b,c,d,f,k,l,m)},Ac:function(){var a=da(Xc),b=S.createProgram();b.name=a;b.Ie=b.Ge=b.He=0;b.Te=1;Xc[a]=b;return a},zc:function(a){var b=da($c);$c[b]=S.createShader(a);return b},yc:function(a){S.cullFace(a)},xc:function(a,b){for(var c=0;c<a;c++){var d=J[b+4*c>>2],f=Wc[d];f&&(S.deleteBuffer(f),f.name=0,Wc[d]=null,d==S.Oe&&(S.Oe=0),d==S.te&&(S.te=0))}},wc:function(a,b){for(var c=0;c<a;++c){var d=J[b+4*c>>2],f=Yc[d];f&&(S.deleteFramebuffer(f),
f.name=0,Yc[d]=null)}},vc:function(a){if(a){var b=Xc[a];b?(S.deleteProgram(b),b.name=0,Xc[a]=null):R(1281)}},uc:function(a,b){for(var c=0;c<a;c++){var d=J[b+4*c>>2],f=bd[d];f&&(S.deleteQuery(f),bd[d]=null)}},tc:function(a,b){for(var c=0;c<a;c++){var d=J[b+4*c>>2],f=bd[d];f&&(S.je.deleteQueryEXT(f),bd[d]=null)}},sc:function(a,b){for(var c=0;c<a;c++){var d=J[b+4*c>>2],f=Zc[d];f&&(S.deleteRenderbuffer(f),f.name=0,Zc[d]=null)}},rc:function(a,b){for(var c=0;c<a;c++){var d=J[b+4*c>>2],f=cd[d];f&&(S.deleteSampler(f),
f.name=0,cd[d]=null)}},qc:function(a){if(a){var b=$c[a];b?(S.deleteShader(b),$c[a]=null):R(1281)}},pc:function(a){if(a){var b=dd[a];b?(S.deleteSync(b),b.name=0,dd[a]=null):R(1281)}},oc:function(a,b){for(var c=0;c<a;c++){var d=J[b+4*c>>2],f=ea[d];f&&(S.deleteTexture(f),f.name=0,ea[d]=null)}},nc:rd,mc:rd,lc:function(a){S.depthMask(!!a)},kc:function(a){S.disable(a)},jc:function(a){S.disableVertexAttribArray(a)},ic:function(a,b,c){S.drawArrays(a,b,c)},hc:function(a,b,c,d){S.drawArraysInstanced(a,b,c,
d)},gc:function(a,b,c,d,f){S.Ve.drawArraysInstancedBaseInstanceWEBGL(a,b,c,d,f)},fc:function(a,b){for(var c=sd[a],d=0;d<a;d++)c[d]=J[b+4*d>>2];S.drawBuffers(c)},ec:td,dc:function(a,b,c,d,f){S.drawElementsInstanced(a,b,c,d,f)},cc:function(a,b,c,d,f,k,l){S.Ve.drawElementsInstancedBaseVertexBaseInstanceWEBGL(a,b,c,d,f,k,l)},bc:function(a,b,c,d,f,k){td(a,d,f,k)},ac:function(a){S.enable(a)},$b:function(a){S.enableVertexAttribArray(a)},_b:function(a){S.endQuery(a)},Zb:function(a){S.je.endQueryEXT(a)},Yb:function(a,
b){return(a=S.fenceSync(a,b))?(b=da(dd),a.name=b,dd[b]=a,b):0},Xb:function(){S.finish()},Wb:function(){S.flush()},Vb:function(a,b,c,d){S.framebufferRenderbuffer(a,b,c,Zc[d])},Ub:function(a,b,c,d,f){S.framebufferTexture2D(a,b,c,ea[d],f)},Tb:function(a){S.frontFace(a)},Sb:function(a,b){ud(a,b,"createBuffer",Wc)},Rb:function(a,b){ud(a,b,"createFramebuffer",Yc)},Qb:function(a,b){ud(a,b,"createQuery",bd)},Pb:function(a,b){for(var c=0;c<a;c++){var d=S.je.createQueryEXT();if(!d){for(R(1282);c<a;)J[b+4*c++>>
2]=0;break}var f=da(bd);d.name=f;bd[f]=d;J[b+4*c>>2]=f}},Ob:function(a,b){ud(a,b,"createRenderbuffer",Zc)},Nb:function(a,b){ud(a,b,"createSampler",cd)},Mb:function(a,b){ud(a,b,"createTexture",ea)},Lb:vd,Kb:vd,Jb:function(a){S.generateMipmap(a)},Ib:function(a,b,c){c?J[c>>2]=S.getBufferParameter(a,b):R(1281)},Hb:function(){var a=S.getError()||hd;hd=0;return a},Gb:function(a,b){xd(a,b,2)},Fb:function(a,b,c,d){a=S.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof
WebGLTexture)a=a.name|0;J[d>>2]=a},K:function(a,b){xd(a,b,0)},Eb:function(a,b,c,d){a=S.getProgramInfoLog(Xc[a]);null===a&&(a="(unknown error)");b=0<b&&d?ka(a,C,d,b):0;c&&(J[c>>2]=b)},Db:function(a,b,c){if(c)if(a>=Vc)R(1281);else if(a=Xc[a],35716==b)a=S.getProgramInfoLog(a),null===a&&(a="(unknown error)"),J[c>>2]=a.length+1;else if(35719==b){if(!a.Ie)for(b=0;b<S.getProgramParameter(a,35718);++b)a.Ie=Math.max(a.Ie,S.getActiveUniform(a,b).name.length+1);J[c>>2]=a.Ie}else if(35722==b){if(!a.Ge)for(b=
0;b<S.getProgramParameter(a,35721);++b)a.Ge=Math.max(a.Ge,S.getActiveAttrib(a,b).name.length+1);J[c>>2]=a.Ge}else if(35381==b){if(!a.He)for(b=0;b<S.getProgramParameter(a,35382);++b)a.He=Math.max(a.He,S.getActiveUniformBlockName(a,b).length+1);J[c>>2]=a.He}else J[c>>2]=S.getProgramParameter(a,b);else R(1281)},Cb:yd,Bb:yd,Ab:function(a,b,c){if(c){a=S.getQueryParameter(bd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;J[c>>2]=d}else R(1281)},zb:function(a,b,c){if(c){a=S.je.getQueryObjectEXT(bd[a],b);var d;
"boolean"==typeof a?d=a?1:0:d=a;J[c>>2]=d}else R(1281)},yb:function(a,b,c){c?J[c>>2]=S.getQuery(a,b):R(1281)},xb:function(a,b,c){c?J[c>>2]=S.je.getQueryEXT(a,b):R(1281)},wb:function(a,b,c){c?J[c>>2]=S.getRenderbufferParameter(a,b):R(1281)},vb:function(a,b,c,d){a=S.getShaderInfoLog($c[a]);null===a&&(a="(unknown error)");b=0<b&&d?ka(a,C,d,b):0;c&&(J[c>>2]=b)},ub:function(a,b,c,d){a=S.getShaderPrecisionFormat(a,b);J[c>>2]=a.rangeMin;J[c+4>>2]=a.rangeMax;J[d>>2]=a.precision},tb:function(a,b,c){c?35716==
b?(a=S.getShaderInfoLog($c[a]),null===a&&(a="(unknown error)"),J[c>>2]=a?a.length+1:0):35720==b?(a=S.getShaderSource($c[a]),J[c>>2]=a?a.length+1:0):J[c>>2]=S.getShaderParameter($c[a],b):R(1281)},S:function(a){var b=ed[a];if(!b){switch(a){case 7939:b=S.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Ad(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=S.getParameter(a))||R(1280);b=b&&Ad(b);break;case 7938:b=S.getParameter(7938);b=2<=v.version?"OpenGL ES 3.0 ("+
b+")":"OpenGL ES 2.0 ("+b+")";b=Ad(b);break;case 35724:b=S.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Ad(b);break;default:R(1280)}ed[a]=b}return b},sb:function(a,b){if(2>v.version)return R(1282),0;var c=fd[a];if(c)return 0>b||b>=c.length?(R(1281),0):c[b];switch(a){case 7939:return c=S.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return Ad(d)}),
c=fd[a]=c,0>b||b>=c.length?(R(1281),0):c[b];default:return R(1280),0}},rb:function(a,b){b=b?kb(C,b):"";if(a=Xc[a]){var c=a,d=c.ze,f=c.bf,k;if(!d)for(c.ze=d={},c.af={},k=0;k<S.getProgramParameter(c,35718);++k){var l=S.getActiveUniform(c,k);var m=l.name;l=l.size;var p=Bd(m);p=0<p?m.slice(0,p):m;var x=c.Te;c.Te+=l;f[p]=[l,x];for(m=0;m<l;++m)d[x]=m,c.af[x++]=p}c=a.ze;d=0;f=b;k=Bd(b);0<k&&(d=parseInt(b.slice(k+1))>>>0,f=b.slice(0,k));if((f=a.bf[f])&&d<f[0]&&(d+=f[1],c[d]=c[d]||S.getUniformLocation(a,b)))return d}else R(1281);
return-1},qb:function(a,b,c){for(var d=sd[b],f=0;f<b;f++)d[f]=J[c+4*f>>2];S.invalidateFramebuffer(a,d)},pb:function(a,b,c,d,f,k,l){for(var m=sd[b],p=0;p<b;p++)m[p]=J[c+4*p>>2];S.invalidateSubFramebuffer(a,m,d,f,k,l)},ob:function(a){return S.isSync(dd[a])},nb:function(a){return(a=ea[a])?S.isTexture(a):0},mb:function(a){S.lineWidth(a)},lb:function(a){a=Xc[a];S.linkProgram(a);a.ze=0;a.bf={}},kb:function(a,b,c,d,f,k){S.Ye.multiDrawArraysInstancedBaseInstanceWEBGL(a,J,b>>2,J,c>>2,J,d>>2,L,f>>2,k)},jb:function(a,
b,c,d,f,k,l,m){S.Ye.multiDrawElementsInstancedBaseVertexBaseInstanceWEBGL(a,J,b>>2,c,J,d>>2,J,f>>2,J,k>>2,L,l>>2,m)},ib:function(a,b){3317==a&&(gd=b);S.pixelStorei(a,b)},hb:function(a,b){S.je.queryCounterEXT(bd[a],b)},gb:function(a){S.readBuffer(a)},fb:function(a,b,c,d,f,k,l){if(2<=v.version)if(S.Oe)S.readPixels(a,b,c,d,f,k,l);else{var m=Cd(k);S.readPixels(a,b,c,d,f,k,m,l>>31-Math.clz32(m.BYTES_PER_ELEMENT))}else(l=Dd(k,f,c,d,l))?S.readPixels(a,b,c,d,f,k,l):R(1280)},eb:function(a,b,c,d){S.renderbufferStorage(a,
b,c,d)},db:function(a,b,c,d,f){S.renderbufferStorageMultisample(a,b,c,d,f)},cb:function(a,b,c){S.samplerParameterf(cd[a],b,c)},bb:function(a,b,c){S.samplerParameteri(cd[a],b,c)},ab:function(a,b,c){S.samplerParameteri(cd[a],b,J[c>>2])},$a:function(a,b,c,d){S.scissor(a,b,c,d)},_a:function(a,b,c,d){for(var f="",k=0;k<b;++k){var l=d?J[d+4*k>>2]:-1,m=J[c+4*k>>2];l=m?kb(C,m,0>l?void 0:l):"";f+=l}S.shaderSource($c[a],f)},Za:function(a,b,c){S.stencilFunc(a,b,c)},Ya:function(a,b,c,d){S.stencilFuncSeparate(a,
b,c,d)},Xa:function(a){S.stencilMask(a)},Wa:function(a,b){S.stencilMaskSeparate(a,b)},Va:function(a,b,c){S.stencilOp(a,b,c)},Ua:function(a,b,c,d){S.stencilOpSeparate(a,b,c,d)},Ta:function(a,b,c,d,f,k,l,m,p){if(2<=v.version)if(S.te)S.texImage2D(a,b,c,d,f,k,l,m,p);else if(p){var x=Cd(m);S.texImage2D(a,b,c,d,f,k,l,m,x,p>>31-Math.clz32(x.BYTES_PER_ELEMENT))}else S.texImage2D(a,b,c,d,f,k,l,m,null);else S.texImage2D(a,b,c,d,f,k,l,m,p?Dd(m,l,d,f,p):null)},Sa:function(a,b,c){S.texParameterf(a,b,c)},Ra:function(a,
b,c){S.texParameterf(a,b,N[c>>2])},Qa:function(a,b,c){S.texParameteri(a,b,c)},Pa:function(a,b,c){S.texParameteri(a,b,J[c>>2])},Oa:function(a,b,c,d,f){S.texStorage2D(a,b,c,d,f)},Na:function(a,b,c,d,f,k,l,m,p){if(2<=v.version)if(S.te)S.texSubImage2D(a,b,c,d,f,k,l,m,p);else if(p){var x=Cd(m);S.texSubImage2D(a,b,c,d,f,k,l,m,x,p>>31-Math.clz32(x.BYTES_PER_ELEMENT))}else S.texSubImage2D(a,b,c,d,f,k,l,m,null);else x=null,p&&(x=Dd(m,l,f,k,p)),S.texSubImage2D(a,b,c,d,f,k,l,m,x)},Ma:function(a,b){S.uniform1f(W(a),
b)},La:function(a,b,c){if(2<=v.version)b&&S.uniform1fv(W(a),N,c>>2,b);else{if(288>=b)for(var d=Ed[b-1],f=0;f<b;++f)d[f]=N[c+4*f>>2];else d=N.subarray(c>>2,c+4*b>>2);S.uniform1fv(W(a),d)}},Ka:function(a,b){S.uniform1i(W(a),b)},Ja:function(a,b,c){if(2<=v.version)b&&S.uniform1iv(W(a),J,c>>2,b);else{if(288>=b)for(var d=Fd[b-1],f=0;f<b;++f)d[f]=J[c+4*f>>2];else d=J.subarray(c>>2,c+4*b>>2);S.uniform1iv(W(a),d)}},Ia:function(a,b,c){S.uniform2f(W(a),b,c)},Ha:function(a,b,c){if(2<=v.version)b&&S.uniform2fv(W(a),
N,c>>2,2*b);else{if(144>=b)for(var d=Ed[2*b-1],f=0;f<2*b;f+=2)d[f]=N[c+4*f>>2],d[f+1]=N[c+(4*f+4)>>2];else d=N.subarray(c>>2,c+8*b>>2);S.uniform2fv(W(a),d)}},Ga:function(a,b,c){S.uniform2i(W(a),b,c)},Fa:function(a,b,c){if(2<=v.version)b&&S.uniform2iv(W(a),J,c>>2,2*b);else{if(144>=b)for(var d=Fd[2*b-1],f=0;f<2*b;f+=2)d[f]=J[c+4*f>>2],d[f+1]=J[c+(4*f+4)>>2];else d=J.subarray(c>>2,c+8*b>>2);S.uniform2iv(W(a),d)}},Ea:function(a,b,c,d){S.uniform3f(W(a),b,c,d)},Da:function(a,b,c){if(2<=v.version)b&&S.uniform3fv(W(a),
N,c>>2,3*b);else{if(96>=b)for(var d=Ed[3*b-1],f=0;f<3*b;f+=3)d[f]=N[c+4*f>>2],d[f+1]=N[c+(4*f+4)>>2],d[f+2]=N[c+(4*f+8)>>2];else d=N.subarray(c>>2,c+12*b>>2);S.uniform3fv(W(a),d)}},Ca:function(a,b,c,d){S.uniform3i(W(a),b,c,d)},Ba:function(a,b,c){if(2<=v.version)b&&S.uniform3iv(W(a),J,c>>2,3*b);else{if(96>=b)for(var d=Fd[3*b-1],f=0;f<3*b;f+=3)d[f]=J[c+4*f>>2],d[f+1]=J[c+(4*f+4)>>2],d[f+2]=J[c+(4*f+8)>>2];else d=J.subarray(c>>2,c+12*b>>2);S.uniform3iv(W(a),d)}},Aa:function(a,b,c,d,f){S.uniform4f(W(a),
b,c,d,f)},za:function(a,b,c){if(2<=v.version)b&&S.uniform4fv(W(a),N,c>>2,4*b);else{if(72>=b){var d=Ed[4*b-1],f=N;c>>=2;for(var k=0;k<4*b;k+=4){var l=c+k;d[k]=f[l];d[k+1]=f[l+1];d[k+2]=f[l+2];d[k+3]=f[l+3]}}else d=N.subarray(c>>2,c+16*b>>2);S.uniform4fv(W(a),d)}},ya:function(a,b,c,d,f){S.uniform4i(W(a),b,c,d,f)},xa:function(a,b,c){if(2<=v.version)b&&S.uniform4iv(W(a),J,c>>2,4*b);else{if(72>=b)for(var d=Fd[4*b-1],f=0;f<4*b;f+=4)d[f]=J[c+4*f>>2],d[f+1]=J[c+(4*f+4)>>2],d[f+2]=J[c+(4*f+8)>>2],d[f+3]=J[c+
(4*f+12)>>2];else d=J.subarray(c>>2,c+16*b>>2);S.uniform4iv(W(a),d)}},wa:function(a,b,c,d){if(2<=v.version)b&&S.uniformMatrix2fv(W(a),!!c,N,d>>2,4*b);else{if(72>=b)for(var f=Ed[4*b-1],k=0;k<4*b;k+=4)f[k]=N[d+4*k>>2],f[k+1]=N[d+(4*k+4)>>2],f[k+2]=N[d+(4*k+8)>>2],f[k+3]=N[d+(4*k+12)>>2];else f=N.subarray(d>>2,d+16*b>>2);S.uniformMatrix2fv(W(a),!!c,f)}},va:function(a,b,c,d){if(2<=v.version)b&&S.uniformMatrix3fv(W(a),!!c,N,d>>2,9*b);else{if(32>=b)for(var f=Ed[9*b-1],k=0;k<9*b;k+=9)f[k]=N[d+4*k>>2],f[k+
1]=N[d+(4*k+4)>>2],f[k+2]=N[d+(4*k+8)>>2],f[k+3]=N[d+(4*k+12)>>2],f[k+4]=N[d+(4*k+16)>>2],f[k+5]=N[d+(4*k+20)>>2],f[k+6]=N[d+(4*k+24)>>2],f[k+7]=N[d+(4*k+28)>>2],f[k+8]=N[d+(4*k+32)>>2];else f=N.subarray(d>>2,d+36*b>>2);S.uniformMatrix3fv(W(a),!!c,f)}},ua:function(a,b,c,d){if(2<=v.version)b&&S.uniformMatrix4fv(W(a),!!c,N,d>>2,16*b);else{if(18>=b){var f=Ed[16*b-1],k=N;d>>=2;for(var l=0;l<16*b;l+=16){var m=d+l;f[l]=k[m];f[l+1]=k[m+1];f[l+2]=k[m+2];f[l+3]=k[m+3];f[l+4]=k[m+4];f[l+5]=k[m+5];f[l+6]=k[m+
6];f[l+7]=k[m+7];f[l+8]=k[m+8];f[l+9]=k[m+9];f[l+10]=k[m+10];f[l+11]=k[m+11];f[l+12]=k[m+12];f[l+13]=k[m+13];f[l+14]=k[m+14];f[l+15]=k[m+15]}}else f=N.subarray(d>>2,d+64*b>>2);S.uniformMatrix4fv(W(a),!!c,f)}},ta:function(a){a=Xc[a];S.useProgram(a);S.lf=a},sa:function(a,b){S.vertexAttrib1f(a,b)},ra:function(a,b){S.vertexAttrib2f(a,N[b>>2],N[b+4>>2])},qa:function(a,b){S.vertexAttrib3f(a,N[b>>2],N[b+4>>2],N[b+8>>2])},pa:function(a,b){S.vertexAttrib4f(a,N[b>>2],N[b+4>>2],N[b+8>>2],N[b+12>>2])},oa:function(a,
b){S.vertexAttribDivisor(a,b)},na:function(a,b,c,d,f){S.vertexAttribIPointer(a,b,c,d,f)},ma:function(a,b,c,d,f,k){S.vertexAttribPointer(a,b,c,!!d,f,k)},la:function(a,b,c,d){S.viewport(a,b,c,d)},ba:function(a,b,c,d){S.waitSync(dd[a],b,(c>>>0)+4294967296*d)},n:Qd,u:Rd,k:Sd,J:Td,R:Ud,Q:Vd,y:Wd,x:Xd,q:Yd,w:Zd,ka:$d,ja:ae,ia:be,aa:(a,b,c,d)=>Kd(a,b,c,d)};
(function(){function a(c){G=c=c.exports;Fa=G.pd;La();Ma=G.sd;Oa.unshift(G.qd);Sa--;r.monitorRunDependencies&&r.monitorRunDependencies(Sa);if(0==Sa&&(null!==Va&&(clearInterval(Va),Va=null),Wa)){var d=Wa;Wa=null;d()}return c}var b={a:ce};Sa++;r.monitorRunDependencies&&r.monitorRunDependencies(Sa);if(r.instantiateWasm)try{return r.instantiateWasm(b,a)}catch(c){Ba("Module.instantiateWasm callback failed with error: "+c),ba(c)}cb(b,function(c){a(c.instance)}).catch(ba);return{}})();
var zd=r._malloc=a=>(zd=r._malloc=G.rd)(a),qc=r._free=a=>(qc=r._free=G.td)(a),pc=a=>(pc=G.ud)(a);r.__embind_initialize_bindings=()=>(r.__embind_initialize_bindings=G.vd)();var de=(a,b)=>(de=G.wd)(a,b),ee=()=>(ee=G.xd)(),fe=a=>(fe=G.yd)(a);r.dynCall_viji=(a,b,c,d,f)=>(r.dynCall_viji=G.Ad)(a,b,c,d,f);r.dynCall_vijiii=(a,b,c,d,f,k,l)=>(r.dynCall_vijiii=G.Bd)(a,b,c,d,f,k,l);r.dynCall_viiiiij=(a,b,c,d,f,k,l,m)=>(r.dynCall_viiiiij=G.Cd)(a,b,c,d,f,k,l,m);
r.dynCall_iiiji=(a,b,c,d,f,k)=>(r.dynCall_iiiji=G.Dd)(a,b,c,d,f,k);r.dynCall_jii=(a,b,c)=>(r.dynCall_jii=G.Ed)(a,b,c);r.dynCall_vij=(a,b,c,d)=>(r.dynCall_vij=G.Fd)(a,b,c,d);r.dynCall_iiij=(a,b,c,d,f)=>(r.dynCall_iiij=G.Gd)(a,b,c,d,f);r.dynCall_iiiij=(a,b,c,d,f,k)=>(r.dynCall_iiiij=G.Hd)(a,b,c,d,f,k);r.dynCall_viij=(a,b,c,d,f)=>(r.dynCall_viij=G.Id)(a,b,c,d,f);r.dynCall_viiij=(a,b,c,d,f,k)=>(r.dynCall_viiij=G.Jd)(a,b,c,d,f,k);
r.dynCall_jiiiiii=(a,b,c,d,f,k,l)=>(r.dynCall_jiiiiii=G.Kd)(a,b,c,d,f,k,l);r.dynCall_jiiiiji=(a,b,c,d,f,k,l,m)=>(r.dynCall_jiiiiji=G.Ld)(a,b,c,d,f,k,l,m);r.dynCall_ji=(a,b)=>(r.dynCall_ji=G.Md)(a,b);r.dynCall_iijj=(a,b,c,d,f,k)=>(r.dynCall_iijj=G.Nd)(a,b,c,d,f,k);r.dynCall_iiji=(a,b,c,d,f)=>(r.dynCall_iiji=G.Od)(a,b,c,d,f);r.dynCall_iijjiii=(a,b,c,d,f,k,l,m,p)=>(r.dynCall_iijjiii=G.Pd)(a,b,c,d,f,k,l,m,p);r.dynCall_iij=(a,b,c,d)=>(r.dynCall_iij=G.Qd)(a,b,c,d);
r.dynCall_vijjjii=(a,b,c,d,f,k,l,m,p,x)=>(r.dynCall_vijjjii=G.Rd)(a,b,c,d,f,k,l,m,p,x);r.dynCall_jiji=(a,b,c,d,f)=>(r.dynCall_jiji=G.Sd)(a,b,c,d,f);r.dynCall_viijii=(a,b,c,d,f,k,l)=>(r.dynCall_viijii=G.Td)(a,b,c,d,f,k,l);r.dynCall_iiiiij=(a,b,c,d,f,k,l)=>(r.dynCall_iiiiij=G.Ud)(a,b,c,d,f,k,l);r.dynCall_iiiiijj=(a,b,c,d,f,k,l,m,p)=>(r.dynCall_iiiiijj=G.Vd)(a,b,c,d,f,k,l,m,p);r.dynCall_iiiiiijj=(a,b,c,d,f,k,l,m,p,x)=>(r.dynCall_iiiiiijj=G.Wd)(a,b,c,d,f,k,l,m,p,x);
function Zd(a,b,c,d,f){var k=ee();try{Ma.get(a)(b,c,d,f)}catch(l){fe(k);if(l!==l+0)throw l;de(1,0)}}function Rd(a,b,c){var d=ee();try{return Ma.get(a)(b,c)}catch(f){fe(d);if(f!==f+0)throw f;de(1,0)}}function Xd(a,b,c){var d=ee();try{Ma.get(a)(b,c)}catch(f){fe(d);if(f!==f+0)throw f;de(1,0)}}function Qd(a,b){var c=ee();try{return Ma.get(a)(b)}catch(d){fe(c);if(d!==d+0)throw d;de(1,0)}}function Wd(a,b){var c=ee();try{Ma.get(a)(b)}catch(d){fe(c);if(d!==d+0)throw d;de(1,0)}}
function Sd(a,b,c,d){var f=ee();try{return Ma.get(a)(b,c,d)}catch(k){fe(f);if(k!==k+0)throw k;de(1,0)}}function be(a,b,c,d,f,k,l,m,p,x){var y=ee();try{Ma.get(a)(b,c,d,f,k,l,m,p,x)}catch(B){fe(y);if(B!==B+0)throw B;de(1,0)}}function Yd(a,b,c,d){var f=ee();try{Ma.get(a)(b,c,d)}catch(k){fe(f);if(k!==k+0)throw k;de(1,0)}}function ae(a,b,c,d,f,k,l){var m=ee();try{Ma.get(a)(b,c,d,f,k,l)}catch(p){fe(m);if(p!==p+0)throw p;de(1,0)}}
function Td(a,b,c,d,f){var k=ee();try{return Ma.get(a)(b,c,d,f)}catch(l){fe(k);if(l!==l+0)throw l;de(1,0)}}function Ud(a,b,c,d,f,k,l){var m=ee();try{return Ma.get(a)(b,c,d,f,k,l)}catch(p){fe(m);if(p!==p+0)throw p;de(1,0)}}function $d(a,b,c,d,f,k){var l=ee();try{Ma.get(a)(b,c,d,f,k)}catch(m){fe(l);if(m!==m+0)throw m;de(1,0)}}function Vd(a,b,c,d,f,k,l,m,p,x){var y=ee();try{return Ma.get(a)(b,c,d,f,k,l,m,p,x)}catch(B){fe(y);if(B!==B+0)throw B;de(1,0)}}var ge;Wa=function he(){ge||ie();ge||(Wa=he)};
function ie(){function a(){if(!ge&&(ge=!0,r.calledRun=!0,!Ga)){eb(Oa);aa(r);if(r.onRuntimeInitialized)r.onRuntimeInitialized();if(r.postRun)for("function"==typeof r.postRun&&(r.postRun=[r.postRun]);r.postRun.length;){var b=r.postRun.shift();Qa.unshift(b)}eb(Qa)}}if(!(0<Sa)){if(r.preRun)for("function"==typeof r.preRun&&(r.preRun=[r.preRun]);r.preRun.length;)Ra();eb(Na);0<Sa||(r.setStatus?(r.setStatus("Running..."),setTimeout(function(){setTimeout(function(){r.setStatus("")},1);a()},1)):a())}}
if(r.preInit)for("function"==typeof r.preInit&&(r.preInit=[r.preInit]);0<r.preInit.length;)r.preInit.pop()();ie();


  return moduleArg.ready
}

);
})();
export default CanvasKitInit;