name: Build and Deploy Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Flutter actions
        uses: subosito/flutter-action@v2
        with:
          #flutter-version: '3.16.0'    # 这里修改为你的 Flutter 版本
          channel: 'master'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows application
        run: dart run msix:create

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: build/windows/runner/Release/

